UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg' WHERE TITLE = 'Pulp Fiction';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/6WRrGYalXXveItfpnipYdayFkQB.jpg' WHERE TITLE = 'The Departed';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/xyXmtuvsoM5J3yNad0nvcetpBdY.jpg' WHERE TITLE = 'The Hobbit: An Unexpected Journey';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/iWak7wT0j6ycCc8lKr4NBz9c7n5.jpg' WHERE TITLE = 'Gone Girl';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/6ITVHoipvxAS8luzKtHTbPaHLtT.jpg' WHERE TITLE = 'Lost in Translation';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/s0OrExdg7i3RLR7oqzHRk4q2kL4.jpg' WHERE TITLE = 'Birdman';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/lzMS0CI3FLQYC5EgJoWeIaEt0lm.jpg' WHERE TITLE = 'The Martian';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/jK65srQczOKTpW62wPxwwKztGgE.jpg' WHERE TITLE = 'The Grand Budapest Hotel';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg' WHERE TITLE = 'Spirited Away';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/lTyikzfGgRX5ZqIfVeT26APYfRL.jpg' WHERE TITLE = 'Jojo Rabbit';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/evPzxMacNWsjkUKQO4NXKe5Rl6a.jpg' WHERE TITLE = 'Zero Dark Thirty';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/6G6nqSW9S7EHA9HrYl0Z8uo2H7f.jpg' WHERE TITLE = 'Pan''s Labyrinth';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/iffzIhuLAO38Po6sh1s6ZEVwlNL.jpg' WHERE TITLE = 'Kill Bill: Volume 1';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/rbZvGN1A1QyZuoKzhCw8QPmf2q0.jpg' WHERE TITLE = 'Shutter Island';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/6G73mNyooWAEQTpckPSnFxFoNmc.jpg' WHERE TITLE = 'The Lord of the Rings: The Two Towers';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/i5H7zusQGsysGQ8i6P361Vnr0n2.jpg' WHERE TITLE = 'Se7en';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/9hxBNoRjEDZGjyR1JpmmtxJWmVU.jpg' WHERE TITLE = 'Marie Antoinette';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/hEQYZq2CDB2LSJVxxlazdBOKeyW.jpg' WHERE TITLE = 'The Revenant';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/33pMXav77ICRnceEBLhL8lXTywv.jpg' WHERE TITLE = 'Napoleon';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/goMGTcitprGu7YD6VZS4lUUwzRA.jpg' WHERE TITLE = 'Isle of Dogs';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg' WHERE TITLE = 'Princess Mononoke';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/vLmHH8jAy8Jq8uBsLucd3592WGh.jpg' WHERE TITLE = 'Thor: Ragnarok';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/off0xgvtfHY82l3MC4mDpCk1APY.jpg' WHERE TITLE = 'The Hurt Locker';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/abirSHwWgKajV3hXhaIR5lcCIXe.jpg' WHERE TITLE = 'The Shape of Water';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg' WHERE TITLE = 'Django Unchained';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/7Nwnmyzrtd0FkcRyPqmdzTPppQa.jpg' WHERE TITLE = 'Wolf of Wall Street';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/mRM2NB0i3wv4HqxXvwIjEVi4Qqq.jpg' WHERE TITLE = 'King Kong';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/c6OLXfKAk5BKeR6broC8pYiCquX.jpg' WHERE TITLE = 'Fight Club';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/6b6UpsOXmjO8mJKYsGTG9HW49CN.jpg' WHERE TITLE = 'The Virgin Suicides';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/9YoLdWeBSxAdR6BqQ5uS88d3FWO.jpg' WHERE TITLE = 'Babel';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/Ar7QuJ7sJEiC0oP3I8fKBKIQD9u.jpg' WHERE TITLE = 'Gladiator';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/xRxSLhhjPG2D8l0BXi0KdN4IvPt.jpg' WHERE TITLE = 'Fantastic Mr. Fox';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/zkThiZAaAie8Lw7RAc5yPTOewBV.jpg' WHERE TITLE = 'My Neighbor Totoro';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/rOJb0yQOCny0bPjg8bCLw8DyAD7.jpg' WHERE TITLE = 'Free Guy';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/5C01GuAmEJp951X7fm66SPBlsxU.jpg' WHERE TITLE = 'Detroit';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/nQQIUwEEqa6sjPvnqcGbjJxbdit.jpg' WHERE TITLE = 'Crimson Peak';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/jwt159hXWA9Q5xpBo8hWb3zwLi7.jpg' WHERE TITLE = 'Reservoir Dogs';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/gILte6Zd7m1YneIr6MVhh30S9pr.jpg' WHERE TITLE = 'Goodfellas';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/vmonG9lV1s3CtmOQmmWUO206Xay.jpg' WHERE TITLE = 'The Lovely Bones';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/2fswjyrY3GEzeoVn6mF8pNeNcgf.jpg' WHERE TITLE = 'The Curious Case of Benjamin Button';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/bzCuOfoZ9ZC9AGLs8ZVZ5yo1X16.jpg' WHERE TITLE = 'Somewhere';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/gNdLJU9TxrpGx4dkZidjys3fyy0.jpg' WHERE TITLE = 'Blade Runner 2049';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/bsYv9IFIGfpAV0oUbe7YTiyxhox.jpg' WHERE TITLE = 'Moonrise Kingdom';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/nv5wwZou159v5OC61i4ElR7OqyY.jpg' WHERE TITLE = 'Howl''s Moving Castle';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/j4TnCy7lNPrE8mX5n5ydCoLA7xW.jpg' WHERE TITLE = 'Next Goal Wins';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/yGOHbICOQwlJ20UjK8F2ChGJjvl.jpg' WHERE TITLE = 'Point Break';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/g0YNGpmlXsgHfhGnJz3c5uyzZ1B.jpg' WHERE TITLE = 'Nightmare Alley';
UPDATE MOVIE SET BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280/xwgBHC2FgoIrQitl8jZwXXdsR9u.jpg' WHERE TITLE = 'Once Upon a Time in Hollywood';
COMMIT;