UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg' WHERE ACTOR_NAME = 'Leonardo DiCaprio';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/oFvZoKI6lvU03n4YoNGAll9rkas.jpg' WHERE ACTOR_NAME = 'Tom Hanks';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8LqG2N6j98lFGMpuYsRUAhOunSd.jpg' WHERE ACTOR_NAME = 'Margot Robbie';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lyUyVARQKhGxaxy0FbPJCQRpiaW.jpg' WHERE ACTOR_NAME = 'Ryan Gosling';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nbccV2pMoyLTCeg5DQip24Eq0Jp.jpg' WHERE ACTOR_NAME = 'Anne Hathaway';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7Pxez9J8fuPd2Mn9kex13YALrCQ.jpg' WHERE ACTOR_NAME = 'Christian Bale';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg' WHERE ACTOR_NAME = 'Robert Downey Jr.';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3bOGNsHlrswhyW79uvIHH1V43JI.jpg' WHERE ACTOR_NAME = 'Chris Evans';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/t7EYLBMWQiIDtCoOYZjvqXV84S5.jpg' WHERE ACTOR_NAME = 'Emma Stone';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/trzgptffGvAlAT6MEu01fz47cLW.jpg' WHERE ACTOR_NAME = 'Ryan Reynolds';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qdfRtvPCj51C9Uy5VEgjgj69JyV.jpg' WHERE ACTOR_NAME = 'Samuel L. Jackson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hlYG0MC6im0MHNq1xixxVilfwyR.jpg' WHERE ACTOR_NAME = 'Uma Thurman';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ajNaPmXVVMJFg9GWmu6MJzTaXdV.jpg' WHERE ACTOR_NAME = 'Brad Pitt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/g5cVxQBAQ3AXt3LhdBXtbbN47Uc.jpg' WHERE ACTOR_NAME = 'Meryl Streep';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg' WHERE ACTOR_NAME = 'Cate Blanchett';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/u38k3hQBDwNX0VA22aQceDp9Iyv.jpg' WHERE ACTOR_NAME = 'Joaquin Phoenix';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3WdOloHpjtjL96uVOhFRRCcYSwq.jpg' WHERE ACTOR_NAME = 'Zendaya';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dFxpwRpmzpVfP1zjluH68DeQhyj.jpg' WHERE ACTOR_NAME = 'Timothee Chalamet';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg' WHERE ACTOR_NAME = 'Florence Pugh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/be1bVF7qGX91a6c5WeRPs5pKXln.jpg' WHERE ACTOR_NAME = 'Idris Elba';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tsk3iKGmMgXIGbRjwf2zYkh8Zkb.jpg' WHERE ACTOR_NAME = 'Saoirse Ronan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sMBpav8cK7t7Nk0yf4tuNOqNUyW.jpg' WHERE ACTOR_NAME = 'Michael B. Jordan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/l5AKkg3H1QhMuXmTTmq1EyjyiRb.jpg' WHERE ACTOR_NAME = 'Awkwafina';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3153CfpgZQXTzCY0i74WpJumMQe.jpg' WHERE ACTOR_NAME = 'John Boyega';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/y40Wu1T742kynOqtwXASc5Qgm49.jpg' WHERE ACTOR_NAME = 'Lupita Nyong''o';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/b5w381C8Z33D1iF30KT4k8tJNsk.jpg' WHERE ACTOR_NAME = 'Adam Driver';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eDuBeSHV0R7vuCnHHXrfa7d7IfB.jpg' WHERE ACTOR_NAME = 'Ana de Armas';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3FfJMIVwXgsIXbAT8ECBSZJAncR.jpg' WHERE ACTOR_NAME = 'Tim Robbins';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/905k0RFzH0Kd6gx8oSxRdnr6FL.jpg' WHERE ACTOR_NAME = 'Morgan Freeman';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg' WHERE ACTOR_NAME = 'Marlon Brando';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/m8HAAjq1T75JypKk0v1FFQn4ysZ.jpg' WHERE ACTOR_NAME = 'Al Pacino';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg' WHERE ACTOR_NAME = 'Robert De Niro';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/d3rIv0y2p0jMsQ7ViR7O1606NZa.jpg' WHERE ACTOR_NAME = 'Robin Wright';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8RZLOyYGsoRe9p44q3xin9QkMHv.jpg' WHERE ACTOR_NAME = 'Keanu Reeves';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2GbXERENPpl5MmlqOLlPVaVtifD.jpg' WHERE ACTOR_NAME = 'Laurence Fishburne';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xD4jTA3KmVp5Rq3aHcymL9DUGjD.jpg' WHERE ACTOR_NAME = 'Carrie-Anne Moss';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5emVgsLFlU6SmeBIFsF2Y7aqwtG.jpg' WHERE ACTOR_NAME = 'Jodie Foster';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cbFWUHhk6pZKTEm48OKVM5awNNn.jpg' WHERE ACTOR_NAME = 'Anthony Hopkins';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aCvBXTAR9B1qRjIRzMBYhhbm1fR.jpg' WHERE ACTOR_NAME = 'Matt Damon';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/soINOuacuiThRb2LyPD4tTWve7C.jpg' WHERE ACTOR_NAME = 'Tom Sizemore';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sRLev3wJioBgun3ZoeAUFpkLy0D.jpg' WHERE ACTOR_NAME = 'Liam Neeson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/k3Dmu49B2akwDvgqy52MOxznI59.jpg' WHERE ACTOR_NAME = 'Ben Kingsley';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sQslzbyYZr4Qjv55VseLbbjpuMY.jpg' WHERE ACTOR_NAME = 'Tom Hulce';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3RX8OBqt3gbvFwKYZqiom4O3Ta6.jpg' WHERE ACTOR_NAME = 'Michael Clarke Duncan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/A6zGbkFjM3uajIakgsSeNTmSKqY.jpg' WHERE ACTOR_NAME = 'David Morse';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nPrUZDEbGQe6jwpVbHKJCXsMd7r.jpg' WHERE ACTOR_NAME = 'Kevin Spacey';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kGslMAWcpv8MKzODhDRDkFE0uX7.jpg' WHERE ACTOR_NAME = 'Annette Bening';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/h1hS5o0cKXF2g9Wjej0RtibMPT0.jpg' WHERE ACTOR_NAME = 'Vivien Leigh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qD6WJzydym7n7fCeL9PGnHe1aEV.jpg' WHERE ACTOR_NAME = 'Clark Gable';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4pk2VbOb2td7iBZyir6Ji46HH4N.jpg' WHERE ACTOR_NAME = 'Humphrey Bogart';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jXEE0P6705JbMAJ2nwtHjmqkd5F.jpg' WHERE ACTOR_NAME = 'Ingrid Bergman';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/e9lGmqQq3EsHeUQgQLByo275hcc.jpg' WHERE ACTOR_NAME = 'Orson Welles';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/djfCB0jPOgmq3w7RD3BMLzWsAu8.jpg' WHERE ACTOR_NAME = 'Joseph Cotten';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7UKRbJBNG7mxBl2QQc5XsAh6F8B.jpg' WHERE ACTOR_NAME = 'Elijah Wood';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5cnnnpnJG6TiYUSS7qgJheUZgnv.jpg' WHERE ACTOR_NAME = 'Ian McKellen';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vH5gVSpHAMhDaFWfh0Q7BG61O1y.jpg' WHERE ACTOR_NAME = 'Viggo Mortensen';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/zMQ93JTLW8KxusKhOlHFZhih3YQ.jpg' WHERE ACTOR_NAME = 'Mark Hamill';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pjBMJVPpcZK23Vt1nzr1zEBTWrP.jpg' WHERE ACTOR_NAME = 'Harrison Ford';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/of4yHmryKPy92eeskUQ7MRmjC3l.jpg' WHERE ACTOR_NAME = 'Carrie Fisher';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/iIfuxalf37xUayuGyK0zG7z6WEZ.jpg' WHERE ACTOR_NAME = 'Sam Neill';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gB9PnGEvxKg33OSlcqptQwTBwPE.jpg' WHERE ACTOR_NAME = 'Laura Dern';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kcyEPgYtBP5Pm6LLeLGfXKjYovL.jpg' WHERE ACTOR_NAME = 'Jeff Goldblum';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dgCABuZp2HBehCT84O4WBp7KIoe.jpg' WHERE ACTOR_NAME = 'Arnold Schwarzenegger';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7FNn9Z5xkRS9EFbGL2tpmpph9xV.jpg' WHERE ACTOR_NAME = 'Linda Hamilton';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2JB4FMgQmnhbBlQ4SxWFN9EIVDi.jpg' WHERE ACTOR_NAME = 'Michael J. Fox';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nxVjpyb3UrfbPZnEyDNlQVlFAs5.jpg' WHERE ACTOR_NAME = 'Christopher Lloyd';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wTSnfktNBLd6kwQxgvkqYw6vEon.jpg' WHERE ACTOR_NAME = 'Sigourney Weaver';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/w3aXr1e7gQCn8MSp1vW4sXHn99P.jpg' WHERE ACTOR_NAME = 'Bruce Willis';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gd7ShD0yt4bsR2STeQ19KQ6hvXL.jpg' WHERE ACTOR_NAME = 'Charlize Theron';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/d81K0RH8UX7tZj49tZaQhZ9ewH.jpg' WHERE ACTOR_NAME = 'Tom Hardy';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/druW5adKddizHNSoPbI0q7Mvn0K.jpg' WHERE ACTOR_NAME = 'Scarlett Johansson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/piQGdoIQOF3C1EI5cbYZLAW1gfj.jpg' WHERE ACTOR_NAME = 'Chris Hemsworth';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5GilHMOt5PAQh6rlUKZzGmaKEI7.jpg' WHERE ACTOR_NAME = 'Mark Ruffalo';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yB84D1neTYXfWBaV0QOE9RF2VCu.jpg' WHERE ACTOR_NAME = 'Jeremy Renner';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ovUKfVOwJ7CadEHaG3NDsfA5xRq.jpg' WHERE ACTOR_NAME = 'Shameik Moore';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/WF7bn6t0LkxwBWyDMWvomVujn7.jpg' WHERE ACTOR_NAME = 'Anthony Gonzalez';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7uEO29wtdyY9bjt2JN43gVpE6vt.jpg' WHERE ACTOR_NAME = 'Gael Garcia Bernal';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/woWhZzFILVhYMAvsPL171HjMY0y.jpg' WHERE ACTOR_NAME = 'Tim Allen';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8iDSGu5l93N7benjf6b3AysBore.jpg' WHERE ACTOR_NAME = 'Albert Brooks';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/z8IEEid4z63CBlJtxrTKEfsW7NA.jpg' WHERE ACTOR_NAME = 'Ellen DeGeneres';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/AeVizz1AfAB2TbsfyzgBvqeSR3G.jpg' WHERE ACTOR_NAME = 'Edward Asner';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tIWUyvmJayu8gtbrzCWC0L3H8kH.jpg' WHERE ACTOR_NAME = 'Cameron Diaz';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qgjMfefsKwSYsyCaIX46uyOXIpy.jpg' WHERE ACTOR_NAME = 'Eddie Murphy';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gjfDl52Kk02MPgUYFjs9bOy33OY.jpg' WHERE ACTOR_NAME = 'Mike Myers';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/papqFgpyroZJEqd7WvuNGN8ti2k.jpg' WHERE ACTOR_NAME = 'Matthew Broderick';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/a7lauBiOZmJEuYDSpfHrJDOgrOc.jpg' WHERE ACTOR_NAME = 'Robby Benson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/iYdeP6K0qz44Wg2Nw9LPJGMBkQ5.jpg' WHERE ACTOR_NAME = 'Robin Williams';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rP74dJXl7EjinGM0shQtUOlH5s2.jpg' WHERE ACTOR_NAME = 'Kristen Bell';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eGsyJmAZNV5tUU4RYy2DIRlFVpW.jpg' WHERE ACTOR_NAME = 'Idina Menzel';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ljQvjbPmcIAl205Lb2Mu4CW8WO7.jpg' WHERE ACTOR_NAME = 'Patton Oswalt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kDf3sW3USjEBDQ3Ua7lbwOfwty6.jpg' WHERE ACTOR_NAME = 'Miles Teller';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ScmKoJ9eiSUOthAt1PDNLi8Fkw.jpg' WHERE ACTOR_NAME = 'J.K. Simmons';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2ojZrkt5rdkUi857WSeCatxXdGS.jpg' WHERE ACTOR_NAME = 'Jesse Eisenberg';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/beO5YvbTjrr5yy8hW26KVDMSr35.jpg' WHERE ACTOR_NAME = 'Andrew Garfield';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/byAo6xoleVSG5O9YpGrQ5YuCRX7.jpg' WHERE ACTOR_NAME = 'Dev Patel';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sX2etBbIkxRaCsATyw5ZpOVMPTD.jpg' WHERE ACTOR_NAME = 'Josh Brolin';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/mCiZNRAzbnPojJEZwVZWLw9kzxR.jpg' WHERE ACTOR_NAME = 'Tommy Lee Jones';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3kNA9VcmymoEwT0btQ4bvMYxzcP.jpg' WHERE ACTOR_NAME = 'Daniel Day-Lewis';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cS7Cbyff6wFVfUGem497vy9LS7A.jpg' WHERE ACTOR_NAME = 'Steve Carell';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tYSja1KByFnZ4Hkp3stPqkKHnNL.jpg' WHERE ACTOR_NAME = 'Michael Keaton';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2DPh6KoNg0p57vvGc6N468zr3ct.jpg' WHERE ACTOR_NAME = 'Rachel McAdams';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5FdalJbrbZ5UCsED5rFrXpvbqJa.jpg' WHERE ACTOR_NAME = 'Colin Farrell';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9tfHL5tholha1YF6bSKt422ETPM.jpg' WHERE ACTOR_NAME = 'Rachel Weisz';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9ZmSejm5lnUVY5IJ1iNx2QEjnHb.jpg' WHERE ACTOR_NAME = 'Mahershala Ali';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/304ilSygaCRWykoBWAL67TOw8g9.jpg' WHERE ACTOR_NAME = 'Casey Affleck';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sXTP6wlqIDz1tDGLU3DFbklSTpq.jpg' WHERE ACTOR_NAME = 'Michelle Williams';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/41TVAcYqKKF7PGf3x7QfaLvkLSW.jpg' WHERE ACTOR_NAME = 'Naomie Harris';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kq5DDnqqofoRI0t6ddtRlsJnNPT.jpg' WHERE ACTOR_NAME = 'Chiwetel Ejiofor';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xvbnUiB2ZBR3QIt595OzNy657Vw.jpg' WHERE ACTOR_NAME = 'Michael Fassbender';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/z6wxnkqSTnzO1tcBui0ss7ehdm9.jpg' WHERE ACTOR_NAME = 'Colin Firth';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/npXFjaFQzBNroCEPllGPTZ5IisA.jpg' WHERE ACTOR_NAME = 'Geoffrey Rush';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aTcqu8cI4wMohU17xTdqmXKTGrw.jpg' WHERE ACTOR_NAME = 'Ben Affleck';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8ykTeTRSYd2MKF5uLBvD93X5KMJ.jpg' WHERE ACTOR_NAME = 'Rami Malek';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/fs7aYUYzzNdilz4JY6wxvIedDIc.jpg' WHERE ACTOR_NAME = 'Lucy Boynton';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pLD2XvxqHueLWOuqXoFngJU3A5H.jpg' WHERE ACTOR_NAME = 'Bradley Cooper';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9Y4Pz7AEXhB9qNar2tMsx5EVXML.jpg' WHERE ACTOR_NAME = 'Lady Gaga';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jj2kZqJobjom36wlhlYhc38nTwN.jpg' WHERE ACTOR_NAME = 'Daniel Kaluuya';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5Jy9HELKS1OYg7moRl8870OSfJq.jpg' WHERE ACTOR_NAME = 'Allison Williams';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/MhBiZbryibwuoEtPL9Ns8pYHC1.jpg' WHERE ACTOR_NAME = 'Winston Duke';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pmVGDb6Yl6OyFcHVGbu1EYNfyFK.jpg' WHERE ACTOR_NAME = 'John Krasinski';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg' WHERE ACTOR_NAME = 'Emily Blunt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lzXRh16qe4HHeBN6tMyw0DHvaMn.jpg' WHERE ACTOR_NAME = 'Toni Collette';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7PMu5zFOEH7PqFDzrKThgKD4Ndf.jpg' WHERE ACTOR_NAME = 'Alex Wolff';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xBXLx1m0uzhXIbY3wN8lmPGeUHl.jpg' WHERE ACTOR_NAME = 'Bill Skarsgard';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/oR7ZJsOHMNFzM1HeugV4a4qCMSF.jpg' WHERE ACTOR_NAME = 'Jaeden Martell';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5Vs7huBmTKftwlsc2BPAntyaQYj.jpg' WHERE ACTOR_NAME = 'Vera Farmiga';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/oym6H2QD9esk4yABjCHaUoNAOa8.jpg' WHERE ACTOR_NAME = 'Patrick Wilson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3qZ09UE7lN6AtorfXFRYpEtSY93.jpg' WHERE ACTOR_NAME = 'Robert Pattinson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/n0mhAgmY6eJQmA7kaugsTZEJgHo.jpg' WHERE ACTOR_NAME = 'Zoe Kravitz';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pbU6qz8eudly20UE6u9T7jUXTgT.jpg' WHERE ACTOR_NAME = 'Ansel Elgort';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2w8tMEdCxBXB44X05RQDC2Kvbap.jpg' WHERE ACTOR_NAME = 'Lily James';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/oX6CpXmnXCHLyqsa4NEed1DZAKx.jpg' WHERE ACTOR_NAME = 'Hugh Jackman';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ufqtnLh3JJjPbEgxEag3MM5nZyv.jpg' WHERE ACTOR_NAME = 'Patrick Stewart';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cRH6HPAQ98PlOwwEvhYO4CM9lwu.jpg' WHERE ACTOR_NAME = 'Chris Pratt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vQBwmsSOAd0JDaEcZ5p43J9xzsY.jpg' WHERE ACTOR_NAME = 'Zoe Saldana';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nL16SKfyP1b7Hk6LsuWiqMfbdb8.jpg' WHERE ACTOR_NAME = 'Chadwick Boseman';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wz3MRiMmoz6b5X3oSzMRC9nLxY1.jpg' WHERE ACTOR_NAME = 'Benedict Cumberbatch';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5OK84Wn1bIEIThFKcVoaN087mLj.jpg' WHERE ACTOR_NAME = 'Tom Holland';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/maf8PhSvDCdEwjEMbYfGpojR5RP.jpg' WHERE ACTOR_NAME = 'Tom Cruise';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/i6fHvGt7Rb8oVyjjdQVV6vEHB94.jpg' WHERE ACTOR_NAME = 'Michelle Yeoh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/iestHyn7PLuVowj5Jaa1SGPboQ4.jpg' WHERE ACTOR_NAME = 'Ke Huy Quan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eWKubKAAssRzmFwCZKh1mdYqGCH.jpg' WHERE ACTOR_NAME = 'Jamie Lee Curtis';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ivUQfhn5olOmR5hthN8C8GThBV4.jpg' WHERE ACTOR_NAME = 'Vincent Cassel';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/d1HVrV8zXy1FJVptmOCkHWG8Jf2.jpg' WHERE ACTOR_NAME = 'Audrey Tautou';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/iExs5h6LeFmdR3kDtSS5xYU1Qgx.jpg' WHERE ACTOR_NAME = 'Alexandre Rodrigues';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aEzWJgEzId04EP8C2UFQaF28WTW.jpg' WHERE ACTOR_NAME = 'Leandro Firmino';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sd7gIA6nEkq6zumkDCfxSE0YSSV.jpg' WHERE ACTOR_NAME = 'Choi Min-sik';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gGGV2gc0orgssYJ0Q9MSomdYo2I.jpg' WHERE ACTOR_NAME = 'Yoo Ji-tae';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ocGoFb6TrK3uWGXt4WnuibUG1vD.jpg' WHERE ACTOR_NAME = 'Gong Yoo';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hmPZhhoeUY89Rys6LrsjpTMeoEN.jpg' WHERE ACTOR_NAME = 'Kim Su-an';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qwbjcyDN37OHiln4a6P4LP31o7F.jpg' WHERE ACTOR_NAME = 'Diego Luna';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wT8cNP0Aip9sEWM9AwSZ9ogJPiT.jpg' WHERE ACTOR_NAME = 'Ivana Baquero';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/n3HcmUflYYaHUiQmzaayi0yqcRf.jpg' WHERE ACTOR_NAME = 'Sergi Lopez';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7hxTsW5CKi2lkz5yGMWShki7DOo.jpg' WHERE ACTOR_NAME = 'Maribel Verdu';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kdqKmnaBDDT0cwTE2C3fKDJrF8D.jpg' WHERE ACTOR_NAME = 'Ulrich Muhe';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ju7H4RLIzfrcMg2e3SUAaA9fEc6.jpg' WHERE ACTOR_NAME = 'Martina Gedeck';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aU6f9UemZsTkqKEG4l77zf6masg.jpg' WHERE ACTOR_NAME = 'Franka Potente';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xg2F0OM9ZTLrEvaQsqFSiMH79WB.jpg' WHERE ACTOR_NAME = 'Moritz Bleibtreu';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/f6PO7Lkrem1N4UmklxHro2k6Jto.jpg' WHERE ACTOR_NAME = 'Francois Cluzet';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/Uuy6WuizieB4fOIGFp0gY90Yq2.jpg' WHERE ACTOR_NAME = 'Omar Sy';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/96dWXnLoCI32jiSSnn2jweaAjBU.jpg' WHERE ACTOR_NAME = 'Peyman Moaadi';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2ryc1fia5FJBACnUZSXh0muxrVO.jpg' WHERE ACTOR_NAME = 'Leila Hatami';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wiZEyqNTNkevCT768bKvvOJvCHb.jpg' WHERE ACTOR_NAME = 'Yalitza Aparicio';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rGGjW1UnUL1Q4TGlfRL3W5yuyq1.jpg' WHERE ACTOR_NAME = 'Marina de Tavira';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9KINm0XIwbt4Qql4oZX55krzKxg.jpg' WHERE ACTOR_NAME = 'Ha Jung-woo';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kBM9UTPYXUA2RNk210DXhztLFns.jpg' WHERE ACTOR_NAME = 'Song Kang-ho';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5VKIhf0ZVxqtrZfyMPbubZz3INr.jpg' WHERE ACTOR_NAME = 'Kim Sang-kyung';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cZ5ybA7cDA0EBMaM5jX2f7RNBVb.jpg' WHERE ACTOR_NAME = 'Toshiro Mifune';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ydyAm2vyBbEPZRICIMqqjDm0NM9.jpg' WHERE ACTOR_NAME = 'Takashi Shimura';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/mWPa6A0JK3tfVRQDIzCQGEao19B.jpg' WHERE ACTOR_NAME = 'Philippe Noiret';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7t59ZGfLUv30DBgoUcqXXhK0t6Y.jpg' WHERE ACTOR_NAME = 'Salvatore Cascio';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ba1Sg02XxCphu6E1dWDMAH1GzeE.jpg' WHERE ACTOR_NAME = 'Roberto Benigni';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9IeE3Iz9HXZVTrvhjSCKlR4FLxB.jpg' WHERE ACTOR_NAME = 'Nicoletta Braschi';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wuwYnv65VbV3ALm7eHCwRFqP83p.jpg' WHERE ACTOR_NAME = 'Pierre Fresnay';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lUoSEdmX6Cl7lLUnV4ewLkVDnhY.jpg' WHERE ACTOR_NAME = 'Erich von Stroheim';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/u16BsGyT6v9yuO7wWAF62NayDth.jpg' WHERE ACTOR_NAME = 'Max von Sydow';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vy5Y0c1ACGCI6d4rVjmTM6HOqNN.jpg' WHERE ACTOR_NAME = 'Gunnar Bjornstrand';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bfLnFfNfMC73Q7WW90xQy2PvRZm.jpg' WHERE ACTOR_NAME = 'Marcello Mastroianni';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gbTVdZGrOwteJ7qYSzyn8XpUk0H.jpg' WHERE ACTOR_NAME = 'Claudia Cardinale';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6EGqmWOR3R3jv3IgrEZmCjTAVGv.jpg' WHERE ACTOR_NAME = 'Bibi Andersson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7IJimLbXIOYpLAS4UaHcNYWRsJe.jpg' WHERE ACTOR_NAME = 'Liv Ullmann';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bkjDaorTT3LcOeTcQF1TDpBlHwt.jpg' WHERE ACTOR_NAME = 'Gustav Frohlich';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/a7mwxoeF34BCxmteoHQSB1ENth0.jpg' WHERE ACTOR_NAME = 'Brigitte Helm';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/uKVNFFt6VA8R7pp7HIPJF4e5PfX.jpg' WHERE ACTOR_NAME = 'Max Schreck';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xlyS30qzcndmczxG5JdJWwJ1heI.jpg' WHERE ACTOR_NAME = 'Werner Krauss';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rmlK341dwK57BVWz1S96tpv7SSF.jpg' WHERE ACTOR_NAME = 'Conrad Veidt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qEuJZiPXKFm1LdtbnHKGj2hQm8a.jpg' WHERE ACTOR_NAME = 'William Holden';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rpRersiDZ1TYjqhKvFALzXflZH8.jpg' WHERE ACTOR_NAME = 'Gloria Swanson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lxxixlFMNH0JuA9K0K3mJmigYcc.jpg' WHERE ACTOR_NAME = 'Fred MacMurray';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xBfikc66lCnShogMZX1k9cV7H26.jpg' WHERE ACTOR_NAME = 'Barbara Stanwyck';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3CU3yG3rCTlG3SwxI9iUOzfHtfX.jpg' WHERE ACTOR_NAME = 'James Stewart';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wQYlkzNBJkvFAY3R0FQZfwLhTDx.jpg' WHERE ACTOR_NAME = 'Kim Novak';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gnz3NGJrUERwklqfuPWXxcOPs0Q.jpg' WHERE ACTOR_NAME = 'Grace Kelly';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lcNAirMFcyM7WIiCmaabjbNZVOJ.jpg' WHERE ACTOR_NAME = 'Cary Grant';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eVkxf868DqzVn9HIlSJHUhRoGA7.jpg' WHERE ACTOR_NAME = 'Eva Marie Saint';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7FipKwmg2woHNvt5ATeXLBirHXs.jpg' WHERE ACTOR_NAME = 'Anthony Perkins';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2dv9IqJEx31RSoH7xAHlJZXF5uB.jpg' WHERE ACTOR_NAME = 'Janet Leigh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6Pj1XkYdI5Wc40Jl0UxJk8PPwlY.jpg' WHERE ACTOR_NAME = 'Tony Curtis';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7jWVWLr1VJqQrN3d4YJaATCIHRw.jpg' WHERE ACTOR_NAME = 'Jack Lemmon';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vcp6rHL2sZWdlJQDEWsEe0jAAe1.jpg' WHERE ACTOR_NAME = 'Marilyn Monroe';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/g98yyY7oGrkocUxxJgOt82I7z6A.jpg' WHERE ACTOR_NAME = 'Gene Kelly';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9Z9DQqNztKlinANGGgD5dQODtlr.jpg' WHERE ACTOR_NAME = 'Debbie Reynolds';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hGXgVxZCMliuHZhVTg2q2UAgrmI.jpg' WHERE ACTOR_NAME = 'Claudette Colbert';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sCVIv2DGoC9U16anTjLwMxKBPZ.jpg' WHERE ACTOR_NAME = 'Peter Sellers';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/iZON8v2ExgNzY943W0UDWXeRZrz.jpg' WHERE ACTOR_NAME = 'George C. Scott';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hL8ep4Hqj6izX7IlzE7Bbcfq62w.jpg' WHERE ACTOR_NAME = 'Malcolm McDowell';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/99xStF5zQy6qkDxLnIVaKD3urzI.jpg' WHERE ACTOR_NAME = 'Patrick Magee';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qkyiLolEqYMGH25xD4sFIXAjZQB.jpg' WHERE ACTOR_NAME = 'Vincent D''Onofrio';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aXFJlEGHlQT7bwxkKwq6Sx7PeEp.jpg' WHERE ACTOR_NAME = 'R. Lee Ermey';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/m2Y3Q0uyuW6htrn2W9UWCWMkpZu.jpg' WHERE ACTOR_NAME = 'Martin Sheen';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/48GB5aISoibd9IYXBO40jrSgFRl.jpg' WHERE ACTOR_NAME = 'Charlie Sheen';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ui8e4sgZAwMPi3hzEO53jyBJF9B.jpg' WHERE ACTOR_NAME = 'Willem Dafoe';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jnqHMaOslt8cef2atSmOpGRvNla.jpg' WHERE ACTOR_NAME = 'Mel Gibson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/b56TRCVVMZ2LMZqzXg0FxeGMd0u.jpg' WHERE ACTOR_NAME = 'Sophie Marceau';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vrzZ41TGNAFgfmZjC2sOJySzBLd.jpg' WHERE ACTOR_NAME = 'Paul Mescal';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jj2Gcobpopokal0YstuCQW0ldJ4.jpg' WHERE ACTOR_NAME = 'Denzel Washington';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2JjRhwG6BEWeF4n9TlvDEDzlP5P.jpg' WHERE ACTOR_NAME = 'Fionn Whitehead';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jJ3KqUW8ySGBwHXOCN3x2Wxjm5W.jpg' WHERE ACTOR_NAME = 'Tom Glynn-Carney';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wnDAg1CyCbBCklQAZ9I1dj5X6QY.jpg' WHERE ACTOR_NAME = 'George MacKay';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xIVxI2ECxxN5J2XNkHPjRax0IHc.jpg' WHERE ACTOR_NAME = 'Dean-Charles Chapman';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qBc7ahQrpVpcllaZ5hkivsOEb3C.jpg' WHERE ACTOR_NAME = 'Adrien Brody';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7M0P39a3CVA22dJyv5YQEkTThU7.jpg' WHERE ACTOR_NAME = 'Thomas Kretschmann';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/o5gVowcjVw4ThYi0L3883Y4X7kH.jpg' WHERE ACTOR_NAME = 'Diane Kruger';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/l9yoDgw3YFC2gMD1HTo5djGOwSY.jpg' WHERE ACTOR_NAME = 'Eric Bana';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/k69IOXdz8PAvaegAI8WYvQvyyUJ.jpg' WHERE ACTOR_NAME = 'Keira Knightley';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/uxiXuVH4vNWrKlJMVVPG1sxAJFe.jpg' WHERE ACTOR_NAME = 'Russell Crowe';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wdmcJagSRJ65AuJ4IUCzuHAdvgy.jpg' WHERE ACTOR_NAME = 'Jennifer Connelly';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yFjTzJHE6AFbwQifOlnNDzmiwlq.jpg' WHERE ACTOR_NAME = 'Dustin Hoffman';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2LoTr6x0TEM7L5em4kSx1VmGDgG.jpg' WHERE ACTOR_NAME = 'Ethan Hawke';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/y3U9QfPN6sJaGl6l68xjwWj28ig.jpg' WHERE ACTOR_NAME = 'Jim Carrey';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6qNnMsKtKz9si5rabpUEG85UfHp.jpg' WHERE ACTOR_NAME = 'Kate Winslet';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/1h2r2VTpoFb5QefAaBYYQgQzL9z.jpg' WHERE ACTOR_NAME = 'Amy Adams';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/a63BgOBKzJ9XPaLFyu7u5Ge3REG.jpg' WHERE ACTOR_NAME = 'Domhnall Gleeson';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dW5U5yrIIPmMjRThR9KT2xH6nTz.jpg' WHERE ACTOR_NAME = 'Oscar Isaac';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xlWpuLgwxMnZEVgV9OID1TkUNtP.jpg' WHERE ACTOR_NAME = 'Clive Owen';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3YF19rWusxWfEI59ZM33dFhasRq.jpg' WHERE ACTOR_NAME = 'Julianne Moore';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/em89OJJvBRX7kNJJPASmNKQujsC.jpg' WHERE ACTOR_NAME = 'Sharlto Copley';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/z2FA8js799xqtfiFjBTicFYdfk.jpg' WHERE ACTOR_NAME = 'Joseph Gordon-Levitt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4rfjISL3Flx16jfiusXoHbpt87X.jpg' WHERE ACTOR_NAME = 'Sandra Bullock';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dt0a7DT0SQeHb7NpURD6ifyEzsN.jpg' WHERE ACTOR_NAME = 'George Clooney';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ct2Gh2sJSxd4yaMrSsqSt1HpIC3.jpg' WHERE ACTOR_NAME = 'Jake Gyllenhaal';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/og4I51GsuwohdPgoELOHVMMqMre.jpg' WHERE ACTOR_NAME = 'Jesse Plemons';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/iTMnXrPfC1rmom6a9q4hy6YSJWG.jpg' WHERE ACTOR_NAME = 'Adam Sandler';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cuRGm9ySxto57ifv3tSAYhOLAYA.jpg' WHERE ACTOR_NAME = 'Julia Fox';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/x3k0HCpMNqEtVf2VKQrSCol1ia2.jpg' WHERE ACTOR_NAME = 'Lakeith Stanfield';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/u69PvpWqGkywSm0YjFiw77j9eqS.jpg' WHERE ACTOR_NAME = 'Amitabh Bachchan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aagrv7LIDWq0GxZelUPqubCg7sH.jpg' WHERE ACTOR_NAME = 'Dharmendra';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dfNRjtvbxisRSBDhCoUMuEFyY3V.jpg' WHERE ACTOR_NAME = 'Hema Malini';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gXmIdkOhJN7pa8XDR7KQJXgtXni.jpg' WHERE ACTOR_NAME = 'Jaya Bachchan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tCEppfUu0g2Luu0rS5VKMoL4eSw.jpg' WHERE ACTOR_NAME = 'Shah Rukh Khan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/h4m0TkDuEMCUNaPrQxMRyFb2AQ7.jpg' WHERE ACTOR_NAME = 'Kajol';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6uiZSwi2kvd1jZ7X7Xz9W9VGuV4.jpg' WHERE ACTOR_NAME = 'Aamir Khan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gaDrAdXxIrbBRCd9cX8YvJDEuLb.jpg' WHERE ACTOR_NAME = 'R. Madhavan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/mQr8ynFFVq08qgQ4aSNl5B0ko8v.jpg' WHERE ACTOR_NAME = 'Sharman Joshi';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eVOziSvi6PLL5vkROHO1sbsKUFW.jpg' WHERE ACTOR_NAME = 'Fatima Sana Shaikh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sQ0VIqGLecfpwYayO05Z7NC32yN.jpg' WHERE ACTOR_NAME = 'Sanya Malhotra';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nYx5T3tkghBPvmI29J2iJlZOFyV.jpg' WHERE ACTOR_NAME = 'Farhan Akhtar';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/d7XGTvyYgmrsA05XOn1YtxYcuY1.jpg' WHERE ACTOR_NAME = 'Hrithik Roshan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/h7eVy3QlTVwbWL10dpY5Y9mVlFB.jpg' WHERE ACTOR_NAME = 'Abhay Deol';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gSNaBg8Q7Nh0u4HhW6pR5B0ujlL.jpg' WHERE ACTOR_NAME = 'Katrina Kaif';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/w1eXF7T60QlEC2gNfr99J3n8CgX.jpg' WHERE ACTOR_NAME = 'Nawazuddin Siddiqui';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hBiAldG2BGMVoZUPbvK3FNDSw22.jpg' WHERE ACTOR_NAME = 'Manoj Bajpayee';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cb15PLOeRNt7uxsiymjHfnJPm3i.jpg' WHERE ACTOR_NAME = 'Richa Chadha';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/GmIRKLKP3xEx1mgF7VrFurIEbz.jpg' WHERE ACTOR_NAME = 'Kangana Ranaut';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qbdclvnDkJxPX7OQqmMY7w9ekBP.jpg' WHERE ACTOR_NAME = 'Ayushmann Khurrana';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cvt5nvCHr1ICf5u8A2mlzLQ8LsV.jpg' WHERE ACTOR_NAME = 'Tabu';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wKPybRcSYcbgDiJZwELudrRNf0r.jpg' WHERE ACTOR_NAME = 'Radhika Apte';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hKSa4DWEAD7DYhABYGwjPmxdpAY.jpg' WHERE ACTOR_NAME = 'Vicky Kaushal';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/43e24aeOC8AZITo6ShaKKG9aV0Y.jpg' WHERE ACTOR_NAME = 'Taapsee Pannu';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qkA9PpWJRw3rNjVkWfNZdwLvRZx.jpg' WHERE ACTOR_NAME = 'Irrfan Khan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7tJoyJygnKOweIlirFCWoOcuSzq.jpg' WHERE ACTOR_NAME = 'Nimrat Kaur';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sRiwLmhduFghJo8U2coUafnDD4C.jpg' WHERE ACTOR_NAME = 'Ranveer Singh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lAgBZgHKTo6amIO9CfNxUbm1usH.jpg' WHERE ACTOR_NAME = 'Alia Bhatt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/A46ekiPFC3vA1442FJmiIudpxX1.jpg' WHERE ACTOR_NAME = 'Vijay Varma';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ttBY7Y8x4NCpXfGS9Tc1NN8ISos.jpg' WHERE ACTOR_NAME = 'Rajkummar Rao';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tFx6DRETklfkFIUu5Sl5TCN1gD9.jpg' WHERE ACTOR_NAME = 'Shraddha Kapoor';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/n7pKtccmf2jVOz8Qn90q2ThqLge.jpg' WHERE ACTOR_NAME = 'Salman Khan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rzvvBQ0r6oiqDdzcsdTRB7jN4Rx.jpg' WHERE ACTOR_NAME = 'Deepika Padukone';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ymYNHV9luwgyrw17NXHqbOWTQkg.jpg' WHERE ACTOR_NAME = 'Ranbir Kapoor';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hh48u9scic0nITGtzi9b6rJeAtT.jpg' WHERE ACTOR_NAME = 'Priyanka Chopra';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qY4GG9zj4JhgoiBaHhT5FIGeHu3.jpg' WHERE ACTOR_NAME = 'Preity Zinta';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/85uKiFDEcIqzLh0GwqYvecXw4uA.jpg' WHERE ACTOR_NAME = 'Saif Ali Khan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gxQjVzLxpxiu5gncrmtGiAaULUi.jpg' WHERE ACTOR_NAME = 'Madhuri Dixit';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/m4bnX5VQs2DfvQsLmfbKbBxUkC9.jpg' WHERE ACTOR_NAME = 'Vidya Balan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/i538HToMEGR6J2OVmOGX3GfWcQC.jpg' WHERE ACTOR_NAME = 'Konkona Sen Sharma';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vnHQQFzTjJ0sv14DGMIoKa3qTxN.jpg' WHERE ACTOR_NAME = 'Ajay Devgn';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kp9xnwDALUt6nuPBGuJHlvnxGnM.jpg' WHERE ACTOR_NAME = 'Kareena Kapoor';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6bm1lhrEgGFpOLBjvcOi3aoQmtg.jpg' WHERE ACTOR_NAME = 'Rani Mukerji';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4qnST3lxsD0kPHCbxfDgmcBDSuC.jpg' WHERE ACTOR_NAME = 'Dilip Kumar';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yparLNMEKMNusOrdnSo9qxQl7K5.jpg' WHERE ACTOR_NAME = 'Meena Kumari';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/fXNA5aCPFClxmiRb3h7QH0OkuQJ.jpg' WHERE ACTOR_NAME = 'Madhubala';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/Uf6j10nvqnDMPbXk3UwYVJWpcA.jpg' WHERE ACTOR_NAME = 'Raj Kapoor';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/t7S8wplP3dPYPC8IvETVcLFBv4p.jpg' WHERE ACTOR_NAME = 'Sunil Dutt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/f3Vxz0QB7PHeyPcXrfJX14Xkxnu.jpg' WHERE ACTOR_NAME = 'Pankaj Tripathi';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bdTjdiCRdnQJOUFoLcAsZKhcb64.jpg' WHERE ACTOR_NAME = 'Bhumi Pednekar';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/znCPPYR79c1DU2MvA61JXhdMeCs.jpg' WHERE ACTOR_NAME = 'Neena Gupta';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vaa4dSmayH71krkgnECXQsPaRre.jpg' WHERE ACTOR_NAME = 'Karisma Kapoor';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yQOKkmQaksa3hOi72MbPnrqz77k.jpg' WHERE ACTOR_NAME = 'Rishi Kapoor';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8Xmfnwe6pf58duYqxxYv81phs2.jpg' WHERE ACTOR_NAME = 'Anushka Sharma';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/17zscZgz4wOlGDd3Gziw4YbI3G.jpg' WHERE ACTOR_NAME = 'Kamal Haasan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cQBcrXqcQPfXOQfNfgO3slJM2xi.jpg' WHERE ACTOR_NAME = 'Rajinikanth';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wmkwZWFHqMptqdt4HacMIAe8OBP.jpg' WHERE ACTOR_NAME = 'Fahadh Faasil';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/a3HWdfCAbplrvoMNEJCjnkbqqOo.jpg' WHERE ACTOR_NAME = 'Vijay Sethupathi';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/z9hCUd4jzSF1WQS4qOCefOcdLwV.jpg' WHERE ACTOR_NAME = 'R. Sarathkumar';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8YkgaUlTshiDWHymBOEXZ948Yyn.jpg' WHERE ACTOR_NAME = 'Trisha';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/o11aBHj4gFkTPgh6zsLHPq67b0b.jpg' WHERE ACTOR_NAME = 'Vikram';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/fzna7CNrtggE9sJLWWOPCHVdCmD.jpg' WHERE ACTOR_NAME = 'Shraddha Srinath';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hwGNxY71w6MWmULoHvhPBWtgmVw.jpg' WHERE ACTOR_NAME = 'Kalidas Jayaram';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ycxl56NbjNkJZkYbUMdwGdnBIg7.jpg' WHERE ACTOR_NAME = 'Karthi';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/d0ApUGeFuGXpBkODIc6eLbBkb7B.jpg' WHERE ACTOR_NAME = 'Narain';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/zbQ1sDRVRHkroWwvrnqYKMerl66.jpg' WHERE ACTOR_NAME = 'Vijay';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ukA3kk56Eqhn8g42an73CgdpXC5.jpg' WHERE ACTOR_NAME = 'Malavika Mohanan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rYuhyicWBWguymMQ5B02IfENdvI.jpg' WHERE ACTOR_NAME = 'Andrea Jeremiah';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/34gv8DThQCh74oZQZe5zoDnaZrw.jpg' WHERE ACTOR_NAME = 'Dhanush';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yM13Up2NnSPHZ03eepxPjWMjsY9.jpg' WHERE ACTOR_NAME = 'Aishwarya Rajesh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hIFXv3gIjlNS78gJmaguEOxvfPH.jpg' WHERE ACTOR_NAME = 'Suriya';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/n8JVr2ToMbTz3XsJ7uo95J3hgCj.jpg' WHERE ACTOR_NAME = 'Jyothika';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qOFycWPpr3Hi4kVXKWnTTKCAnGk.jpg' WHERE ACTOR_NAME = 'Gautham Vasudev Menon';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ksMHimRUMXLwJqrZsgGx9TzyQiN.jpg' WHERE ACTOR_NAME = 'Vikranth';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qDKUEHZRsVgbXKJjuziUnZcOC1L.jpg' WHERE ACTOR_NAME = 'Kishore';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2pGgJ8TowhQfFG6So3pdbN6QCXT.jpg' WHERE ACTOR_NAME = 'Anandhi';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cQNlW5ztPIANrUNRos81cxZuZe5.jpg' WHERE ACTOR_NAME = 'Kathir';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/z8mU71yAUfVLgKWHorsTIsyQwnt.jpg' WHERE ACTOR_NAME = 'Samuthirakani';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/q0Rw0e9RogMD0zJ0Heq0GotDYoy.jpg' WHERE ACTOR_NAME = 'Rana Daggubati';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/86c6MtUIxsUWjKow3TrVUQHlE4L.jpg' WHERE ACTOR_NAME = 'Sasikumar';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yc1PWTXrJEisKpb9OGK5J6I8LMP.jpg' WHERE ACTOR_NAME = 'Attakathi Dinesh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/u6RVP8ukgLaymeoi5VmX0JRAcCn.jpg' WHERE ACTOR_NAME = 'Prabhas';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/zpe6Es8kdNOXuPdXiJvqxzsmN6z.jpg' WHERE ACTOR_NAME = 'Anushka Shetty';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/t4WYoKiFAyO1Rhjv7O03EKmJHp4.jpg' WHERE ACTOR_NAME = 'Tamannaah';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7C1bj7z3XhqxjDIGoCs6MFJdSVa.jpg' WHERE ACTOR_NAME = 'Ramya Krishnan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5ycQgZ3SPUa12bq0yn1jpToBq9X.jpg' WHERE ACTOR_NAME = 'N. T. Rama Rao Jr.';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/twGqYUCR0Yh33j3TcgRTZRBRhTd.jpg' WHERE ACTOR_NAME = 'Ram Charan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8oVIWyIoFUal8SJFnmCUtkkm1HP.jpg' WHERE ACTOR_NAME = 'Vijay Deverakonda';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/x0VLQqGuQocLALiauiZV2wge3OI.jpg' WHERE ACTOR_NAME = 'Shalini Pandey';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/FFGYlhLQK7FWzPLtmOb1QHTDAh.jpg' WHERE ACTOR_NAME = 'Samantha Ruth Prabhu';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wHr3bKhYpiDiYVMZLZqebeauEVw.jpg' WHERE ACTOR_NAME = 'Allu Arjun';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lj16BGfdqygHF8PZVt2KO8GUXn1.jpg' WHERE ACTOR_NAME = 'Rashmika Mandanna';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bm72k6FmDxhxtZsl1xvxoz88Hkm.jpg' WHERE ACTOR_NAME = 'Jagapathi Babu';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jfOH4sUWs3VXuGUlo0VLMYNRBQ4.jpg' WHERE ACTOR_NAME = 'Nani';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wvoBULQimwguAGPOHZ8TDoy7jBJ.jpg' WHERE ACTOR_NAME = 'Mohanlal';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/c5ewp9XtDIOwK5QWhwA7TD0GzqO.jpg' WHERE ACTOR_NAME = 'Mammootty';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/v8duBiKG9cfOy3RX1cW6JnrLuDe.jpg' WHERE ACTOR_NAME = 'Nivin Pauly';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/s4kqCkKKsrwrzzoTCNelyEHQYAE.jpg' WHERE ACTOR_NAME = 'Nazriya Nazim';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cKngC3leAnZRXTzg0N8N2DYn4HY.jpg' WHERE ACTOR_NAME = 'Dulquer Salmaan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eFMA1PFOpDtiJ5MlkSAMexvTPsl.jpg' WHERE ACTOR_NAME = 'Soubin Shahir';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/oPsXUtaE0ZslhaGRdtww0ZpMRe7.jpg' WHERE ACTOR_NAME = 'Sreenath Bhasi';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/r1tiqFWXlWDFlZx966yOeBYs2qY.jpg' WHERE ACTOR_NAME = 'Nimisha Sajayan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dKRa8ghSXw6J1OTcxMziZh3l1jb.jpg' WHERE ACTOR_NAME = 'Antony Varghese';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bDVEN345ccxDhcWD47a9qh0a7WH.jpg' WHERE ACTOR_NAME = 'Sudheesh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/32YxjXVmgkPCVKUQAkNqWUGbBIl.jpg' WHERE ACTOR_NAME = 'Indrajith Sukumaran';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7u1WgUHnwIW9mtL6aTdo1cRXmCM.jpg' WHERE ACTOR_NAME = 'Manju Warrier';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/26P7CfxRs6Hay7xAkHAghDtvGzO.jpg' WHERE ACTOR_NAME = 'Vinay Forrt';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pjomXVYzHd62IuduDc9UVS82sBb.jpg' WHERE ACTOR_NAME = 'Soumitra Chatterjee';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ta2slxvbMeVGgIgDjmA7p9ZCBqR.jpg' WHERE ACTOR_NAME = 'Subir Banerjee';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pm4DcNLgkzzuHO53mi1BEuYnliv.jpg' WHERE ACTOR_NAME = 'Karuna Banerjee';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yUmZUJVPPxFyUDC53bvfKpDk7Dq.jpg' WHERE ACTOR_NAME = 'Chhabi Biswas';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nqjJEBXvhA5E4bivtrcWP3berAv.jpg' WHERE ACTOR_NAME = 'Madhabi Mukherjee';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/m2MFSVdx4aKVoLRFPJoO5u0FMon.jpg' WHERE ACTOR_NAME = 'Sharmila Tagore';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xJLs751advRY19Vx6t6oX5MA635.jpg' WHERE ACTOR_NAME = 'Rinku Ghosh';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tCF3MBCmpiFN4ftF7PDzfzNGUEu.jpg' WHERE ACTOR_NAME = 'Rinku Rajguru';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8yNhmEagtRnDIEg07r8CahQy3PU.jpg' WHERE ACTOR_NAME = 'Akash Thosar';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pHOZJIY2lPSQitStiEZXRjVW1RF.jpg' WHERE ACTOR_NAME = 'Bulbul Ahmed';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/s7H2vvDpzoPph0IYpQ3JBzm9LwT.jpg' WHERE ACTOR_NAME = 'Golam Mustafa';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/t5A3efpAnKGOtmkzW2l9jkFA8yl.jpg' WHERE ACTOR_NAME = 'Farooque';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/r5MWHqX1cxibytL7KGXNaT2NlD1.jpg' WHERE ACTOR_NAME = 'Shabana';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/46ebiphxjeUP4T1JCGp6G4DAyQL.jpg' WHERE ACTOR_NAME = 'Chanchal Chowdhury';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6rQ5XEIG9wsBiI025blQ3aC8ZJG.jpg' WHERE ACTOR_NAME = 'Jaya Ahsan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4244ytl7IddA1dva36I9RopC0u4.jpg' WHERE ACTOR_NAME = 'Ferdous Ahmed';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6cGP2k6wblQqwyfGdPWyFDWr0wT.jpg' WHERE ACTOR_NAME = 'Mosharraf Karim';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/mQsL3mzv4IeJhoj6q4QUTjsTlHM.jpg' WHERE ACTOR_NAME = 'Fazlur Rahman Babu';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/v5gbJBs0vTH2x1MHsVXwr30qf48.jpg' WHERE ACTOR_NAME = 'Nusrat Imrose Tisha';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hHKkmaNQtvSV3cNeBpm9wHcTn55.jpg' WHERE ACTOR_NAME = 'Tariq Anam Khan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/chH09tG9J8ZhOm8XM21CgO0uyaq.jpg' WHERE ACTOR_NAME = 'Azmeri Haque Badhon';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pQ7hUTR4LAeYhQIgQbhyYQopA79.jpg' WHERE ACTOR_NAME = 'Mostafa Monwar';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/8qWyYqP4H81YyfBP2iTJX83OGGI.jpg' WHERE ACTOR_NAME = 'Ilias Kanchan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xaFWmjP6kOygJw0K0Bp3tvF73L9.jpg' WHERE ACTOR_NAME = 'Shabnur';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eSErLKimeBiLD7Vkv6AWAmbcWxp.jpg' WHERE ACTOR_NAME = 'Riaz';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/q81NHmiOHdyDWvfvIh4GK7q5I1v.jpg' WHERE ACTOR_NAME = 'Nirab Hossain';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/1YLSDO84dJazHEHpMyT6FclWqt1.jpg' WHERE ACTOR_NAME = 'Jayanto Chattopadhyay';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tIMZ3fc0uttC7qEfIeSZsdOOJGB.jpg' WHERE ACTOR_NAME = 'Zahid Hasan';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vx4WLoVlVEaCVclQdKteMYCHo2z.jpg' WHERE ACTOR_NAME = 'Iresh Zaker';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2O6yfkpnBMxp1Q5CS649N310KPf.jpg' WHERE ACTOR_NAME = 'Shahiduzzaman Selim';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/m5rs3UmHaK7W7OfJOjnBtu7oF0v.jpg' WHERE ACTOR_NAME = 'Parsa Evana';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/L111ffXC7xn0gRB8auzMiTGdrt.jpg' WHERE ACTOR_NAME = 'Sunerah Binte Kamal';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4gSLuSAkUMnjv0nRRgUjOGSo2YU.jpg' WHERE ACTOR_NAME = 'Siam Ahmed';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7xhYs2NQjQcNt1PChhK9FqbCWFr.jpg' WHERE ACTOR_NAME = 'Sabila Nur';
UPDATE ACTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lAMdlcB9adhszLvzBF7rIjtsWUt.jpg' WHERE ACTOR_NAME = 'Nusraat Faria';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg' WHERE DIRECTOR_NAME = 'Christopher Nolan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tZxcg19YQ3e8fJ0pOs7hjlnmmr6.jpg' WHERE DIRECTOR_NAME = 'Steven Spielberg';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2Hh4Jos62luf90CCglP5K32qaWO.jpg' WHERE DIRECTOR_NAME = 'James Cameron';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/zdDx9Xs93UIrJFWYApYR28J8M6b.jpg' WHERE DIRECTOR_NAME = 'Denis Villeneuve';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dxKAhpkz4XNwmRzMG5QOpXjPZ1N.jpg' WHERE DIRECTOR_NAME = 'Greta Gerwig';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/stwnTvZAoD8gEJEDHpDQyLCyDy5.jpg' WHERE DIRECTOR_NAME = 'Bong Joon-ho';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xbINBnWn28YygYWUJ1aSAw0xPRv.jpg' WHERE DIRECTOR_NAME = 'Anthony Russo';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/o0OXjFzL10jCy89iAs7UzzSbyoK.jpg' WHERE DIRECTOR_NAME = 'Joe Russo';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vITDphkNpSn1LP5gUEheAnlclnl.jpg' WHERE DIRECTOR_NAME = 'Pete Docter';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg' WHERE DIRECTOR_NAME = 'Quentin Tarantino';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/g3DjfKsgZQWZiw30I20hZVk1oMX.jpg' WHERE DIRECTOR_NAME = 'Martin Scorsese';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bNc908d59Ba8VDNr4eCcm4G1cR.jpg' WHERE DIRECTOR_NAME = 'Peter Jackson';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tpEczFclQZeKAiCeKZZ0adRvtfz.jpg' WHERE DIRECTOR_NAME = 'David Fincher';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dzHC2LxmarkBxWLhjp2DRa5oCev.jpg' WHERE DIRECTOR_NAME = 'Sofia Coppola';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5Mx0RilUcVjXzmeKYAZJJ0WXZMQ.jpg' WHERE DIRECTOR_NAME = 'Alejandro Inarritu';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/zABJmN9opmqD4orWl3KSdCaSo7Q.jpg' WHERE DIRECTOR_NAME = 'Ridley Scott';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/s03CeUeC5yAXyB1acqP0zGNo2SC.jpg' WHERE DIRECTOR_NAME = 'Wes Anderson';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ouhjt9KugzhWtdEyBPipihB3ic8.jpg' WHERE DIRECTOR_NAME = 'Hayao Miyazaki';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ww6L2ksfJNMbuiIdDuvVKndUHsv.jpg' WHERE DIRECTOR_NAME = 'Taika Waititi';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ee1zr5G7L54lvtjGCD2JUyyk4UX.jpg' WHERE DIRECTOR_NAME = 'Kathryn Bigelow';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cWvt8FdPAH0j3QtLzAN1j7ZJJrr.jpg' WHERE DIRECTOR_NAME = 'Guillermo del Toro';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vZ50guP86otYTiBSGfi35GNHWVf.jpg' WHERE DIRECTOR_NAME = 'Frank Darabont';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/IwGgkmW6IoJ9vuNF0T9CU3FYUX.jpg' WHERE DIRECTOR_NAME = 'Francis Ford Coppola';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lPYDQ5LYNJ12rJZENtyASmVZ1Ql.jpg' WHERE DIRECTOR_NAME = 'Robert Zemeckis';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4nE4ttPQBuw1virOz0LYT08c1Vm.jpg' WHERE DIRECTOR_NAME = 'Lana Wachowski';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rCScAjSpeKA19BLNR07MqNNeeTT.jpg' WHERE DIRECTOR_NAME = 'Lilly Wachowski';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/w9Lw3xTEFQUYELkl9AH5i3p5OhJ.jpg' WHERE DIRECTOR_NAME = 'Jonathan Demme';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5z89X9rB76JDblqMQ52fviwXxAN.jpg' WHERE DIRECTOR_NAME = 'Sam Mendes';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kwMaOpQnirmXFEuvP0t7Zc94sqj.jpg' WHERE DIRECTOR_NAME = 'Victor Fleming';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/AnxPuEsdjPTJ6uIaHY0KdgBeu7t.jpg' WHERE DIRECTOR_NAME = 'Michael Curtiz';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/e9lGmqQq3EsHeUQgQLByo275hcc.jpg' WHERE DIRECTOR_NAME = 'Orson Welles';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg' WHERE DIRECTOR_NAME = 'George Lucas';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/imtFUtcASoh2e1Emtt62UuFkIWA.jpg' WHERE DIRECTOR_NAME = 'Irvin Kershner';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eEalDQpLsXJqejPDQ3MWGe95UHT.jpg' WHERE DIRECTOR_NAME = 'Richard Marquand';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yVfDkVbgQHD1A7JSV8Z47EjB1mU.jpg' WHERE DIRECTOR_NAME = 'John McTiernan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/35NQ8HjFXQlGYDz9UkhT08lKl5C.jpg' WHERE DIRECTOR_NAME = 'George Miller';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tAcIXWQWgGzoSsw2BUBuDbCGgii.jpg' WHERE DIRECTOR_NAME = 'Joss Whedon';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tnx7iMVydPQXGOoLsxXl84PXtbA.jpg' WHERE DIRECTOR_NAME = 'Jon Favreau';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jmpNVUvvhJB2X2eOSKpveFnetM8.jpg' WHERE DIRECTOR_NAME = 'Bob Persichetti';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/crb297utC6W4HSstOe5djDPTwEN.jpg' WHERE DIRECTOR_NAME = 'Lee Unkrich';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xlrE4VD2VbZCDpaNdWCpH1ZihPS.jpg' WHERE DIRECTOR_NAME = 'John Lasseter';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/fo6ePCWEVB0L1sccrvB99Iaoqcg.jpg' WHERE DIRECTOR_NAME = 'Andrew Stanton';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/zB9Uz0Rs1K9uwHffXRFaBwwSYI.jpg' WHERE DIRECTOR_NAME = 'Brad Bird';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/opLn7bTvqUOkio2OrZU5Ejam6cV.jpg' WHERE DIRECTOR_NAME = 'Jennifer Yuh Nelson';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ponaYm3Xr1Pki8JVDSIzfA4NkNw.jpg' WHERE DIRECTOR_NAME = 'Chris Buck';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/14kRZ3XxNMyBv717YQSXr3wCucy.jpg' WHERE DIRECTOR_NAME = 'Damien Chazelle';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/b5qQpFHmgNyvV1t81ou17Jt2fRj.jpg' WHERE DIRECTOR_NAME = 'Danny Boyle';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rgVaJNkZCgMarUcZuUAsVfXMWk3.jpg' WHERE DIRECTOR_NAME = 'Joel Coen';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/lbL8LEcvuxNrzda37g3mysOS2qS.jpg' WHERE DIRECTOR_NAME = 'Ethan Coen';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wKAs2LtLYSUzt3ZZ8pnxMwuEWuR.jpg' WHERE DIRECTOR_NAME = 'Paul Thomas Anderson';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/vOyZXNJq7Oo01LPtSD5AZHjctgH.jpg' WHERE DIRECTOR_NAME = 'Adam McKay';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cEA6cxG3AiH0hUzFH9mUQQVy20O.jpg' WHERE DIRECTOR_NAME = 'Tom McCarthy';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pNCt2m8jfiX3YOiCdnJT3OPxNvm.jpg' WHERE DIRECTOR_NAME = 'Noah Baumbach';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4eIorZhYSIAnGUCOjRv45nB08FG.jpg' WHERE DIRECTOR_NAME = 'Kenneth Lonergan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6nld5eQwiJmuLmyesk4EUeCaoo3.jpg' WHERE DIRECTOR_NAME = 'Barry Jenkins';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xUxg7SAM17eEc0rF90gz59Ap0w1.jpg' WHERE DIRECTOR_NAME = 'Steve McQueen';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3PDYOFfk5NLmNcEz6SFZmdmqVZr.jpg' WHERE DIRECTOR_NAME = 'Peter Farrelly';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/w9Z3dlJDtWBXo4rIxGI0XY896j2.jpg' WHERE DIRECTOR_NAME = 'Tom Hooper';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aTcqu8cI4wMohU17xTdqmXKTGrw.jpg' WHERE DIRECTOR_NAME = 'Ben Affleck';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ts06thbCv9Ug2mNpcbcrmLGRL4Q.jpg' WHERE DIRECTOR_NAME = 'Bryan Singer';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kFUKn5g3ebpyZ3CSZZZo2HFWRNQ.jpg' WHERE DIRECTOR_NAME = 'Jordan Peele';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pmVGDb6Yl6OyFcHVGbu1EYNfyFK.jpg' WHERE DIRECTOR_NAME = 'John Krasinski';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/45lOHyHwdMgyKm6u3jwLtyfwOjc.jpg' WHERE DIRECTOR_NAME = 'Ari Aster';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4ndnP2NNavhfGtJqihD4FVDsYMY.jpg' WHERE DIRECTOR_NAME = 'Andy Muschietti';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bNJccMIKzCtYnndcOKniSKCzo5Y.jpg' WHERE DIRECTOR_NAME = 'James Wan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/A6FPht87DiqXzp456WjakLi2AtP.jpg' WHERE DIRECTOR_NAME = 'Todd Phillips';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pk0GDjn99crNwR4qgCCEokDYd71.jpg' WHERE DIRECTOR_NAME = 'James Mangold';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pnKqZub3IlKYbyH9RRTMDOoqEn0.jpg' WHERE DIRECTOR_NAME = 'James Gunn';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dux4DCDaL6c639DTXGiV7nm1wcN.jpg' WHERE DIRECTOR_NAME = 'Ryan Coogler';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/caapCMfXLifC7XveUiY653xWBsZ.jpg' WHERE DIRECTOR_NAME = 'Scott Derrickson';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/fkXChMX6CUXY1yOxBehAzvaTCl7.jpg' WHERE DIRECTOR_NAME = 'Jon Watts';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/oWLUXWY0j8TYzwnf2wETYWO181S.jpg' WHERE DIRECTOR_NAME = 'Joseph Kosinski';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rVAZLUZhuKCmdzhCsSiOf8j64IA.jpg' WHERE DIRECTOR_NAME = 'Daniel Kwan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rb59IHeLhmyBgTeBH5LGXXIt3Y8.jpg' WHERE DIRECTOR_NAME = 'Daniel Scheinert';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5rA459xpMt6IeJG7ZqvhLbSozEH.jpg' WHERE DIRECTOR_NAME = 'Matt Reeves';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eRCryGwKDH4XqUlrdkERmeBWPo8.jpg' WHERE DIRECTOR_NAME = 'Chad Stahelski';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3BqgbeAkNnDcIVtrDvG6LJnEkZK.jpg' WHERE DIRECTOR_NAME = 'Edgar Wright';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3FRBEdKKlxhvPWPt0jzgmSjeHwn.jpg' WHERE DIRECTOR_NAME = 'Mathieu Kassovitz';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4DhPaNaxYnkgxVJHVLyL5gKmKpG.jpg' WHERE DIRECTOR_NAME = 'Jean-Pierre Jeunet';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/usc1zwBXEHN4A6rkvJcmgWpc7rS.jpg' WHERE DIRECTOR_NAME = 'Fernando Meirelles';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jsSFCVB7MhuVbSLwTgESiXEiNjt.jpg' WHERE DIRECTOR_NAME = 'Park Chan-wook';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dLP1p4AkU1zwJkDboct58Uub9S7.jpg' WHERE DIRECTOR_NAME = 'Yeon Sang-ho';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5Mx0RilUcVjXzmeKYAZJJ0WXZMQ.jpg' WHERE DIRECTOR_NAME = 'Alejandro Gonzalez Inarritu';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/3IuSW8NazUH3VlM8KYwMhTTk5lV.jpg' WHERE DIRECTOR_NAME = 'Florian Henckel von Donnersmarck';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7Upo7OK9T1jKkpjXnZHA7bhgwlN.jpg' WHERE DIRECTOR_NAME = 'Tom Tykwer';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cLfpk5eIT8h7NnZcz6Iti3DPkRu.jpg' WHERE DIRECTOR_NAME = 'Olivier Nakache';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9axN13gdsRpQLKqmvibsc9jqK2q.jpg' WHERE DIRECTOR_NAME = 'Eric Toledano';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/mCEpFbimAvhiR3P91h5b8UEUhY.jpg' WHERE DIRECTOR_NAME = 'Asghar Farhadi';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/gaHhrzPfxfc3cbQLkDt54gtP3n1.jpg' WHERE DIRECTOR_NAME = 'Alfonso Cuaron';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/g2iwSho2vJxVz7cbD1FAKAmPD6A.jpg' WHERE DIRECTOR_NAME = 'Akira Kurosawa';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/t5PurTT9QuvV5Xs9Q2JzVui5oqF.jpg' WHERE DIRECTOR_NAME = 'Giuseppe Tornatore';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ba1Sg02XxCphu6E1dWDMAH1GzeE.jpg' WHERE DIRECTOR_NAME = 'Roberto Benigni';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ePLyIIgSud1ZhhaLtj1yFo2diC4.jpg' WHERE DIRECTOR_NAME = 'Jean Renoir';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/r0GTpMWUrxgPRbMmv38mNggOBvA.jpg' WHERE DIRECTOR_NAME = 'Federico Fellini';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9dz4PmFzlSyexldWrOXBLLpkBqB.jpg' WHERE DIRECTOR_NAME = 'Fritz Lang';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/keLp43iiIkkllroUwExIJITeR7a.jpg' WHERE DIRECTOR_NAME = 'F.W. Murnau';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hljvbcgEYOHJM6FI5r6Vi2OULwg.jpg' WHERE DIRECTOR_NAME = 'Robert Wiene';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ks9uuDtKu9m9w50t18PamLZ91to.jpg' WHERE DIRECTOR_NAME = 'Sergei Eisenstein';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nWV9BDDCbRegP7etiPjl3vYnJEq.jpg' WHERE DIRECTOR_NAME = 'Billy Wilder';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/108fiNM6poRieMg7RIqLJRxdAwG.jpg' WHERE DIRECTOR_NAME = 'Alfred Hitchcock';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/g98yyY7oGrkocUxxJgOt82I7z6A.jpg' WHERE DIRECTOR_NAME = 'Gene Kelly';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hvRi8etQyf6Zfh7MRsRP0pBR9Om.jpg' WHERE DIRECTOR_NAME = 'Stanley Donen';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/1OTZ7CEdEawDgA4qiBidpWTKE2x.jpg' WHERE DIRECTOR_NAME = 'Frank Capra';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yFT0VyIelI9aegZrsAwOG5iVP4v.jpg' WHERE DIRECTOR_NAME = 'Stanley Kubrick';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/zn4XrQMUg32poFHJd2kwlXBPmGg.jpg' WHERE DIRECTOR_NAME = 'Oliver Stone';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jnqHMaOslt8cef2atSmOpGRvNla.jpg' WHERE DIRECTOR_NAME = 'Mel Gibson';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kICHgrSh4eiICjz8piy9fTXIgph.jpg' WHERE DIRECTOR_NAME = 'Gus Van Sant';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/tDKn6gAgvARdQRfuem2JwyNcP3B.jpg' WHERE DIRECTOR_NAME = 'Ron Howard';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4U9DhwQtrs2UUFPya2ixaYh091i.jpg' WHERE DIRECTOR_NAME = 'Michel Gondry';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/x2QeqEXvi3QjgTybvZ4mmqUf4qO.jpg' WHERE DIRECTOR_NAME = 'Spike Jonze';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qSWzYnDw68xm4i5xprH9BwQ6q25.jpg' WHERE DIRECTOR_NAME = 'Alex Garland';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yj40QEEfjbRFnlwY0XunocNKdAe.jpg' WHERE DIRECTOR_NAME = 'Neill Blomkamp';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ggwlJvCn0laNGjcvwGchuwC00hQ.jpg' WHERE DIRECTOR_NAME = 'Rian Johnson';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5pPcmwI7GMZ45CyrYLJ3n0IXm6e.jpg' WHERE DIRECTOR_NAME = 'Doug Liman';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2qeYBWtDDnkUDOiSsE43wwViwSt.jpg' WHERE DIRECTOR_NAME = 'Jean-Marc Vallee';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/jrTdXoo1NWxG2t0iFwdP5LLbJNV.jpg' WHERE DIRECTOR_NAME = 'Josh Safdie';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/u10A5DpUYRB1zMF7YoGYcyvhois.jpg' WHERE DIRECTOR_NAME = 'Benny Safdie';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/cI0ToZpcju84KjmXSzRuTD8a9V2.jpg' WHERE DIRECTOR_NAME = 'Ramesh Sippy';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eXYKfA6bg12pn9LPrWeRfxYQwcb.jpg' WHERE DIRECTOR_NAME = 'Aditya Chopra';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/s48qPtQJVXdwrVfezMIiyowl3eT.jpg' WHERE DIRECTOR_NAME = 'Ashutosh Gowariker';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wNnmF3mzG7kyaTYuFr5uMpHIJSw.jpg' WHERE DIRECTOR_NAME = 'Rajkumar Hirani';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/h80yPI8rDKlUk29dWFFl6Is8J0P.jpg' WHERE DIRECTOR_NAME = 'Nitesh Tiwari';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wS1aF7dFDnKC44ZbFkbDcIpmFq5.jpg' WHERE DIRECTOR_NAME = 'Anurag Kashyap';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ukj424TfDZCrRwYwQVAWl2nJ3ON.jpg' WHERE DIRECTOR_NAME = 'Zoya Akhtar';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dSq2u9LkYyFzLf5PwwLTciKbwLj.jpg' WHERE DIRECTOR_NAME = 'Vikas Bahl';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/wSm4CkL6LxdDxg7t1kBzy0Gi8Fs.jpg' WHERE DIRECTOR_NAME = 'Sriram Raghavan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rWvTtDwSoKgTy3zSeZoMWGRkNmw.jpg' WHERE DIRECTOR_NAME = 'Anubhav Sinha';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/9diynmZ1i5y8g5OhgevWmik5lEe.jpg' WHERE DIRECTOR_NAME = 'Meghna Gulzar';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7SSh0FR3KX0T326iH8MOHDS28ns.jpg' WHERE DIRECTOR_NAME = 'Aanand L. Rai';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/b7n68jbzVAN68CJSI8ubERlToli.jpg' WHERE DIRECTOR_NAME = 'Ashwiny Iyer Tiwari';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2CRk2UX3KfqMythuLBleMwQ7bQr.jpg' WHERE DIRECTOR_NAME = 'Tigmanshu Dhulia';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qPskSZxvoYflC8Bye4tGNBSroy5.jpg' WHERE DIRECTOR_NAME = 'S. S. Rajamouli';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/dEb8XJGaIqWf2eLaj4ecUlC3b2Z.jpg' WHERE DIRECTOR_NAME = 'Vetrimaaran';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/h7six8EKeZtmlEwwWmCuAi9oNqV.jpg' WHERE DIRECTOR_NAME = 'Mari Selvaraj';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yym15SAcSzIe6xzxOWCgDWiSaZN.jpg' WHERE DIRECTOR_NAME = 'Lokesh Kanagaraj';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4wnvpMpX9ZkSQaLj9PysKPIUQNr.jpg' WHERE DIRECTOR_NAME = 'Pa. Ranjith';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/htgisnF8RSLL6kbwaYlSjyIhVsU.jpg' WHERE DIRECTOR_NAME = 'Karthik Subbaraj';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4ZYlGFIgqzY2510TKcfzIGDAGiD.jpg' WHERE DIRECTOR_NAME = 'Nalan Kumarasamy';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/1Q827qAGjW4OL8v1F5XcOZyvKry.jpg' WHERE DIRECTOR_NAME = 'Thiagarajan Kumararaja';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/sdloJVOR5PYwXQTLl5UihynYh9m.jpg' WHERE DIRECTOR_NAME = 'T. J. Gnanavel';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ofsmrUzaSqEK5JXmbAdSD21uaYS.jpg' WHERE DIRECTOR_NAME = 'Sudha Kongara';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eVqfEqWk8V8RLzQmBT3Tng5yWPK.jpg' WHERE DIRECTOR_NAME = 'Vasanthabalan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/2g65eG5FBh9oOMAhxpfk5T6um6A.jpg' WHERE DIRECTOR_NAME = 'Mysskin';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xNq4APGSj5BmBdbIfJZjN8aJKXJ.jpg' WHERE DIRECTOR_NAME = 'Shankar';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/7TztELIhekyJrR9jxLyuqBYZ5TF.jpg' WHERE DIRECTOR_NAME = 'Sukumar';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/ik1rXY6ci6i7LDm9cV178W3txgb.jpg' WHERE DIRECTOR_NAME = 'Sandeep Reddy Vanga';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/i8FMmDxo2tXbKyrpAJWxokeClWI.jpg' WHERE DIRECTOR_NAME = 'Trivikram Srinivas';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qPskSZxvoYflC8Bye4tGNBSroy5.jpg' WHERE DIRECTOR_NAME = 'Rajamouli';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/uSvFpc0b6jbpFRrkAnXmVgKOzdA.jpg' WHERE DIRECTOR_NAME = 'Koratala Siva';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/yA5HYmJGGwMXqMRAXrzHbkJNAfv.jpg' WHERE DIRECTOR_NAME = 'Gowtam Tinnanuri';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/47Hqs5fHKFU0uRb0qIJOncAcqNl.jpg' WHERE DIRECTOR_NAME = 'Jeethu Joseph';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bzeQl6cLi0XwnXMynIRBwqeOjNn.jpg' WHERE DIRECTOR_NAME = 'Madhu C. Narayanan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bizV6LQMKMCEAVzeIh5rEOty7av.jpg' WHERE DIRECTOR_NAME = 'Alphonse Puthren';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bWtffI3hVjbjuTbxqnUD1hF8bgI.jpg' WHERE DIRECTOR_NAME = 'Anjali Menon';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/o9FdqNyBc7Z2wZJYvm4H7MKwTM0.jpg' WHERE DIRECTOR_NAME = 'Lijo Jose Pellissery';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/m7Cr6VhwS5wYRWxBpGkX4oUwxFw.jpg' WHERE DIRECTOR_NAME = 'Sameer Thahir';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/mXCnvBbRynOYOE3aqGostSvCZ0N.jpg' WHERE DIRECTOR_NAME = 'Dileesh Pothan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/rjjuaQped2aUcnXtWWT4TgH8erJ.jpg' WHERE DIRECTOR_NAME = 'Jeo Baby';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/1xhG42QU8tMQRTDdP1Ed3y9GRvm.jpg' WHERE DIRECTOR_NAME = 'Prithviraj Sukumaran';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/qP5mjuc3dL8n9c1zeY4W6L2w38L.jpg' WHERE DIRECTOR_NAME = 'Satyajit Ray';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nSMHoWBbqWaztUpYRXm7ysKd4Y4.jpg' WHERE DIRECTOR_NAME = 'Ritwik Ghatak';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/zI3EZRn8tHpMzrhCkfk0QX2hDhu.jpg' WHERE DIRECTOR_NAME = 'Nagraj Manjule';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xhlPhxtA7kSlUcndYycmpx6sqqx.jpg' WHERE DIRECTOR_NAME = 'Zahir Raihan';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/n9V1abeVgD4s5QgDxQSPTIv9oag.jpg' WHERE DIRECTOR_NAME = 'Alamgir Kabir';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/5AC1o0IM1HWgOJVQDXtY95EO1ip.jpg' WHERE DIRECTOR_NAME = 'Tanvir Mokammel';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/hBrZV7djlnaVtQHNGwxxcuagizG.jpg' WHERE DIRECTOR_NAME = 'Humayun Ahmed';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/fBT5QkDNkzGN9Cppgt1L5qvU6QL.jpg' WHERE DIRECTOR_NAME = 'Tauquir Ahmed';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6ooPMUQPJo5wO62RgIwHKgeIqsv.jpg' WHERE DIRECTOR_NAME = 'Chashi Nazrul Islam';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/eHuoL5BuVYAtMIuaKQFS15NxNLi.jpg' WHERE DIRECTOR_NAME = 'Khan Ataur Rahman';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xkpa1wfo6Vw0e51TQZVg3Go7xiy.jpg' WHERE DIRECTOR_NAME = 'Morshedul Islam';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/kB8ZcaO8PQtE5zrsiUPEimLVYMo.jpg' WHERE DIRECTOR_NAME = 'Tareque Masud';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aycYl4zyNQRllrphkRQA3yW4k9A.jpg' WHERE DIRECTOR_NAME = 'Catherine Masud';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/bkjcviQhIfuFRKXz7a9E0yUSktZ.jpg' WHERE DIRECTOR_NAME = 'Mostofa Sarwar Farooki';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/aGU7xxqEReryg2N6a27Fq6yGH8x.jpg' WHERE DIRECTOR_NAME = 'Giasuddin Selim';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/pktRwUMW5PoqGFLpfulDfFg5YeN.jpg' WHERE DIRECTOR_NAME = 'Abu Shahed Emon';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/uOSr7q2hXYWfGyGMvDiol6Rs0qN.jpg' WHERE DIRECTOR_NAME = 'Rubaiyat Hossain';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/6r7hTXs0sYiD1VpuWlg2EHNHM8Q.jpg' WHERE DIRECTOR_NAME = 'Rezwan Shahriar Sumit';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/xBvYoyk8ORvfMKZBwZhnpcCws6N.jpg' WHERE DIRECTOR_NAME = 'Kamar Ahmad Simon';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/4bundLnsnpHswaFaaSkbdhb5V1W.jpg' WHERE DIRECTOR_NAME = 'Mejbaur Rahman Sumon';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/mmJAGzMuf4be130W0ZQZY3jxHBe.jpg' WHERE DIRECTOR_NAME = 'Raihan Rafi';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/nzLBGo8yfdby9J6Q4vUeXU68n9Z.jpg' WHERE DIRECTOR_NAME = 'Iqbal Chowdhury';
UPDATE DIRECTOR SET PHOTO_URL = 'https://image.tmdb.org/t/p/w500/phm3Wt2FR5RxXrXhGLG3RFjUUxP.jpg' WHERE DIRECTOR_NAME = 'Shihab Shaheen';
COMMIT;