UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=L2NAh3CIdig' WHERE TITLE = 'Avengers: Endgame';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=PqPNksLZIAk' WHERE TITLE = 'Babel';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Y1IgAEejvqM' WHERE TITLE = 'Barbie';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=egYzOALlYyU' WHERE TITLE = 'Birdman';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=geFtxCSz8xI' WHERE TITLE = 'Blade Runner 2049';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=vLWsNDZqXpo' WHERE TITLE = 'Crimson Peak';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=yv74LqiumXE' WHERE TITLE = 'Detroit';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_iH0UBYDI4g' WHERE TITLE = 'Django Unchained';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=U2Qp5pL3ovA' WHERE TITLE = 'Dune: Part Two';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=VuIaCvIFWIA' WHERE TITLE = 'Fantastic Mr. Fox';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=dfeUzm6KF4g' WHERE TITLE = 'Fight Club';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=cttnRmcr_ME' WHERE TITLE = 'Free Guy';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=P5ieIbInFpg' WHERE TITLE = 'Gladiator';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=2-_-1nJf8Vg' WHERE TITLE = 'Gone Girl';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=PTBRNXGQR9Q' WHERE TITLE = 'Goodfellas';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ARCQf2CEr8k' WHERE TITLE = 'Howl''s Moving Castle';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=JE9z-gy4De4' WHERE TITLE = 'Inception';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=1HFv47QHWJU' WHERE TITLE = 'Inside Out';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=LY19rHKAaAg' WHERE TITLE = 'Interstellar';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=dt__kig8PVU' WHERE TITLE = 'Isle of Dogs';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=tL4McUzXfFI' WHERE TITLE = 'Jojo Rabbit';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=sXwXk3jcrfU' WHERE TITLE = 'Kill Bill: Volume 1';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=9extfjDZCts' WHERE TITLE = 'King Kong';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=1s4YQqnbnM8' WHERE TITLE = 'Lost in Translation';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=yBWyKRoh98U' WHERE TITLE = 'Marie Antoinette';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=RBCRe73dZb0' WHERE TITLE = 'Moonrise Kingdom';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_nv94fL_IA8' WHERE TITLE = 'My Neighbor Totoro';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=KPr42qEdhnU' WHERE TITLE = 'Napoleon';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=jFkaH84fOJo' WHERE TITLE = 'Next Goal Wins';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Q81Yf46Oj3s' WHERE TITLE = 'Nightmare Alley';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=vKgITiP1UMg' WHERE TITLE = 'Once Upon a Time in Hollywood';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=qiuSBWVdgLI' WHERE TITLE = 'Oppenheimer';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=bM9QabAojCg' WHERE TITLE = 'Parasite';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=OBGKGm3RYos' WHERE TITLE = 'Pan''s Labyrinth';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=KywiWyPjrOg' WHERE TITLE = 'Point Break';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=I1dHzoRl0sQ' WHERE TITLE = 'Princess Mononoke';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=tGpTpVyI_OQ' WHERE TITLE = 'Pulp Fiction';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=2KLZ4fSXtgI' WHERE TITLE = 'Reservoir Dogs';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=KPOuJGkpblk' WHERE TITLE = 'Se7en';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=qdPw9x9h5CY' WHERE TITLE = 'Shutter Island';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=iEga7Hz9a3U' WHERE TITLE = 'Somewhere';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=GAp2_0JJskk' WHERE TITLE = 'Spirited Away';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=lqijVXvw7_E' WHERE TITLE = 'The Curious Case of Benjamin Button';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_PZpmTj1Q8Q' WHERE TITLE = 'The Dark Knight';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=r-MiSNsCdQ4' WHERE TITLE = 'The Departed';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=G1jG8HUY4zI' WHERE TITLE = 'The Grand Budapest Hotel';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=CXqZK-nbZ74' WHERE TITLE = 'The Hobbit: An Unexpected Journey';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=4mgWq9wZs2o' WHERE TITLE = 'The Hurt Locker';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=nuTU5XcZTLA' WHERE TITLE = 'The Lord of the Rings: The Two Towers';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=QydPyttFzhs' WHERE TITLE = 'The Lovely Bones';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ej3ioOneTy8' WHERE TITLE = 'The Martian';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=EhffABvfAW0' WHERE TITLE = 'The Revenant';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=oRKnlUanptY' WHERE TITLE = 'The Shape of Water';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=8kDcCGlaBwY' WHERE TITLE = 'The Virgin Suicides';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ue80QwXMRHg' WHERE TITLE = 'Thor: Ragnarok';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=wO44qBPBG4c' WHERE TITLE = 'Titanic';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Slj4-Sv-YNA' WHERE TITLE = 'Wolf of Wall Street';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=k7R2uVZYebE' WHERE TITLE = 'Zero Dark Thirty';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=PLl99DlL6b4' WHERE TITLE = 'The Shawshank Redemption';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Ew9ngL1GZvs' WHERE TITLE = 'The Godfather';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=9O1Iy9od7-A' WHERE TITLE = 'The Godfather Part II';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Mj9IA9tTfio' WHERE TITLE = 'Forrest Gump';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=FVI84Dfx2-I' WHERE TITLE = 'The Matrix';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=6iB21hsprAQ' WHERE TITLE = 'The Silence of the Lambs';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=RYExstiQlLc' WHERE TITLE = 'Saving Private Ryan';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=v0RB-3sWbBA' WHERE TITLE = 'Schindler''s List';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Bg7epsq0OIQ' WHERE TITLE = 'The Green Mile';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=XCxzXblZyfQ' WHERE TITLE = 'American Beauty';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=h2oX0zQA67U' WHERE TITLE = 'Gone with the Wind';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=MF7JH_54d8c' WHERE TITLE = 'Casablanca';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=fAcLNMkzfTE' WHERE TITLE = 'Citizen Kane';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_nZdmwHrcnw' WHERE TITLE = 'The Lord of the Rings: The Fellowship of the Ring';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=zckJCxYxn1g' WHERE TITLE = 'The Lord of the Rings: The Return of the King';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=i-vsILeJ8_8' WHERE TITLE = 'Star Wars: Episode IV - A New Hope';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=vU6L3jXt2r8' WHERE TITLE = 'The Empire Strikes Back';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=MAW1E3JIQZE' WHERE TITLE = 'Return of the Jedi';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Rz_FvTXa_qY' WHERE TITLE = 'Jurassic Park';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=BuBD2s2NmEM' WHERE TITLE = 'Terminator 2: Judgment Day';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ez6WQ7IX72U' WHERE TITLE = 'Back to the Future';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=sVwH0hIvV5k' WHERE TITLE = 'Alien';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=8OxirbuHsBA' WHERE TITLE = 'Aliens';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=4Wi28Vsi_ZU' WHERE TITLE = 'Die Hard';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=MonFNCgK4WE' WHERE TITLE = 'Mad Max: Fury Road';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=hIR8Ar-Z4hw' WHERE TITLE = 'The Avengers';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=8ugaeA-nMTc' WHERE TITLE = 'Iron Man';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=tg52up16eq0' WHERE TITLE = 'Spider-Man: Into the Spider-Verse';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Rvr68u6k5sI' WHERE TITLE = 'Coco';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=QftAW9TTmuQ' WHERE TITLE = 'Toy Story';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=6c3K7LhA9Yc' WHERE TITLE = 'Toy Story 3';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=SPHfeNgogVs' WHERE TITLE = 'Finding Nemo';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Ajcdb4FAL7A' WHERE TITLE = 'Up';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=NwGEF8B6Bcw' WHERE TITLE = 'WALL-E';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ppDwfm6e498' WHERE TITLE = 'Shrek';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=lFzVJEksoDY' WHERE TITLE = 'The Lion King';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=UUVpyeS_fVw' WHERE TITLE = 'Beauty and the Beast';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=mq05scD6PUs' WHERE TITLE = 'Aladdin';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=TbQm5doF_Uc' WHERE TITLE = 'Frozen';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=NgsQ8mVkN8w' WHERE TITLE = 'Ratatouille';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Q7kZy3T6vRM' WHERE TITLE = 'Whiplash';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_oBwwSXdO_E' WHERE TITLE = 'La La Land';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=rBCNU0XT9GY' WHERE TITLE = 'The Social Network';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=AIzbwV7on6Q' WHERE TITLE = 'Slumdog Millionaire';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=A0oNrgumrlE' WHERE TITLE = 'No Country for Old Men';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=-bEwlq_7f4s' WHERE TITLE = 'There Will Be Blood';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=1kQc3mmtH-o' WHERE TITLE = 'The Big Short';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=WgnrwwiIDlI' WHERE TITLE = 'Spotlight';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=BHi-a1n8t7M' WHERE TITLE = 'Marriage Story';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=NxQmuJnrjxg' WHERE TITLE = 'Manchester by the Sea';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=9NJj12tJzqc' WHERE TITLE = 'Moonlight';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=z02Ie8wKKRg' WHERE TITLE = '12 Years a Slave';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=QkZxoko_HC0' WHERE TITLE = 'Green Book';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=HXMqX9s67kY' WHERE TITLE = 'The King''s Speech';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=3RrtxIci4T0' WHERE TITLE = 'Argo';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=27zlBpzdOZg' WHERE TITLE = 'Bohemian Rhapsody';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=UywJmJ6ohvc' WHERE TITLE = 'A Star Is Born';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=gsB70ZRY-hI' WHERE TITLE = 'Get Out';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=xaEzoWyeR3Y' WHERE TITLE = 'Us';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=rqEnM25BsNQ' WHERE TITLE = 'A Quiet Place';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=MJNR58zaStE' WHERE TITLE = 'Hereditary';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=xKJmEC5ieOk' WHERE TITLE = 'It';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=k10ETZ41q5o' WHERE TITLE = 'The Conjuring';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=-RFFRxcoKfA' WHERE TITLE = 'Joker';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=XaE_9pfybL4' WHERE TITLE = 'Logan';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=3CqymRQ1uUU' WHERE TITLE = 'Guardians of the Galaxy';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=xjDjIWPwcPU' WHERE TITLE = 'Black Panther';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=HSzx-zryEgM' WHERE TITLE = 'Doctor Strange';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=1mTjfMFyPi8' WHERE TITLE = 'Spider-Man: No Way Home';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Klc__shdj88' WHERE TITLE = 'Top Gun: Maverick';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=wxN1T1uxQ2g' WHERE TITLE = 'Everything Everywhere All at Once';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=vc7_mH2PWHs' WHERE TITLE = 'The Batman';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=6r0s41Ju5XA' WHERE TITLE = 'John Wick';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=jGGptGEAo2U' WHERE TITLE = 'Baby Driver';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=FKwcXt3JIaU' WHERE TITLE = 'La Haine';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=555A7T_kmIc' WHERE TITLE = 'Amélie';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=dcUOO4Itgmw' WHERE TITLE = 'City of God';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=tAaBkFChaRg' WHERE TITLE = 'Oldboy';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=4qm59Rcq1Fw' WHERE TITLE = 'Train to Busan';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_P29GF_NbDc' WHERE TITLE = 'Amores Perros';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=jAE7dNurHR4' WHERE TITLE = 'The Shining';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=inc0vS58ZKg' WHERE TITLE = 'Y Tu Mamá También';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=n3_iLOp6IhM' WHERE TITLE = 'The Lives of Others';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ZCYnsUdO6H0' WHERE TITLE = 'Run Lola Run';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=dvdJ--DV0Uo' WHERE TITLE = 'The Intouchables';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=58Onuy5USTc' WHERE TITLE = 'A Separation';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=27gpqR5ADUs' WHERE TITLE = 'Roma';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=wYsdzNIcJNc' WHERE TITLE = 'The Handmaiden';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=0n_HQwQU8ls' WHERE TITLE = 'Memories of Murder';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=L2E_DfExUmU' WHERE TITLE = 'Rashomon';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=RsRN65PlaIM' WHERE TITLE = 'Seven Samurai';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=geKhyNerWM8' WHERE TITLE = 'Ikiru';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=JMyVSD6OvO8' WHERE TITLE = 'Cinema Paradiso';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=pAYEQP8gx3w' WHERE TITLE = 'Life Is Beautiful';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=vZucwtdSvJ8' WHERE TITLE = 'The Seventh Seal';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=zzEDWwhtAHc' WHERE TITLE = '8½';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=8ZO01M8k1mg' WHERE TITLE = 'Persona';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ZAvzaOxDt2c' WHERE TITLE = 'Metropolis';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=nulvWqYUM8k' WHERE TITLE = 'Nosferatu';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=RDY97iu1_q8' WHERE TITLE = 'Sholay';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=oIZ4U21DRlM' WHERE TITLE = 'Dilwale Dulhania Le Jayenge';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=rZPbpymefuE' WHERE TITLE = 'Lagaan';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=zIKu9k50SDo' WHERE TITLE = '3 Idiots';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=x_7YlGv9u1g' WHERE TITLE = 'Dangal';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=SOXWc32k4zA' WHERE TITLE = 'PK';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=cSfNfckoXPc' WHERE TITLE = 'Gangs of Wasseypur';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=FJrpcDgC3zU' WHERE TITLE = 'Zindagi Na Milegi Dobara';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=CnWgjtNWKXI' WHERE TITLE = 'Queen';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=2iVYI99VGaw' WHERE TITLE = 'Andhadhun';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=lJxLudSPxsQ' WHERE TITLE = 'The Lunchbox';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=JfbxcD6biOk' WHERE TITLE = 'Gully Boy';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=tn_2Ie_jtX8' WHERE TITLE = 'Taare Zameen Par';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=l-BTOTtcGmk' WHERE TITLE = 'Rang De Basanti';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=CUj73MLqZoQ' WHERE TITLE = 'Kahaani';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Cg8sbRFS3zU' WHERE TITLE = 'Uri: The Surgical Strike';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=T3BBEX_pyQA' WHERE TITLE = 'Pink';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=SKJfBo3xMW0' WHERE TITLE = 'Masaan';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=yU6zMPFd4UU' WHERE TITLE = 'Newton';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ZjuhALyNgss' WHERE TITLE = 'Tumbbad';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=gzeaGcLLl_A' WHERE TITLE = 'Stree';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=vc7AZNWvs0M' WHERE TITLE = 'Swades';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=tVMAQAsjsOU' WHERE TITLE = 'Kal Ho Naa Ho';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=8tuHQWGMQwY' WHERE TITLE = 'Devdas';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=rARol7Dk2zo' WHERE TITLE = 'Chennai Express';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=X_5_BLt76c0' WHERE TITLE = 'Padmaavat';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=6PjoLgcrmcQ' WHERE TITLE = 'Mughal-E-Azam';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=jJf35tEkW9E' WHERE TITLE = 'Vikram';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=CmuEqjuzxWc' WHERE TITLE = 'Master';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=tP_dh_s27iw' WHERE TITLE = 'Kaithi';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=1sVr-uWZPjE' WHERE TITLE = 'Vikram Vedha';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=DWwvAmVbuEI' WHERE TITLE = 'Super Deluxe';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=GMNsUxJe4R4' WHERE TITLE = 'Pariyerum Perumal';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=4mnzK2KIz9U' WHERE TITLE = 'Visaranai';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=fYKLIjpfuwQ' WHERE TITLE = 'Enthiran';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=3NQRhE772b0' WHERE TITLE = 'Baahubali: The Beginning';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=qD-6d8Wo3do' WHERE TITLE = 'Baahubali 2: The Conclusion';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=i4pjiLGUTtk' WHERE TITLE = 'RRR';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=aozErj9NqeE' WHERE TITLE = 'Arjun Reddy';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=sueMmTm-M4Y' WHERE TITLE = 'Rangasthalam';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=ou6h-22tMnA' WHERE TITLE = 'Pushpa: The Rise';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=x-1ZoU1xB4I' WHERE TITLE = 'Eega';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_LaejRruLKI' WHERE TITLE = 'Magadheera';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=6tC1yOUvvMo' WHERE TITLE = 'Jersey';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=EtXlAVd-uBQ' WHERE TITLE = 'Drishyam';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=3P4BFBSafF0' WHERE TITLE = 'Kumbalangi Nights';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=uVpHL5g4buY' WHERE TITLE = 'Bangalore Days';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_KY8Du4WWew' WHERE TITLE = 'Maheshinte Prathikaram';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=xD4GMBTDssU' WHERE TITLE = 'Jallikattu';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=k_E6ctiFn6I' WHERE TITLE = 'The Great Indian Kitchen';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=mgv68E_o6VM' WHERE TITLE = 'Pather Panchali';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=mgv68E_o6VM' WHERE TITLE = 'Aparajito';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=mgv68E_o6VM' WHERE TITLE = 'Apur Sansar';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=gFCuy_FUsdo' WHERE TITLE = 'Charulata';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=xVgXiC2hOkg' WHERE TITLE = 'Goopy Gyne Bagha Byne';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=iShPI_JF524' WHERE TITLE = 'Sairat';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=5a8nYE9Q_Vg' WHERE TITLE = 'Titas Ekti Nadir Naam';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=nFBIJYEiUO4' WHERE TITLE = 'Monpura';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=Q5N2ZuEppf0' WHERE TITLE = 'Third Person Singular Number';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=6s1dRyQ8Zbo' WHERE TITLE = 'Television';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=zfTM48zbi_c' WHERE TITLE = 'Aynabaji';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=yvUCSoN9Zv8' WHERE TITLE = 'Dhaka Attack';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=_v9eIPXXBig' WHERE TITLE = 'Debi';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=PtF6gvcF1Hs' WHERE TITLE = 'Fagun Hawa';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=A14bJ2ljHVg' WHERE TITLE = 'Made in Bangladesh';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=WZNCRsVhvx8' WHERE TITLE = 'Rehana Maryam Noor';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=YonjB5ZZmKc' WHERE TITLE = 'Poran';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=uDXcDGLelXk' WHERE TITLE = 'Damal';
UPDATE MOVIE SET TRAILER_URL = 'https://www.youtube.com/watch?v=oy7FY3k3TJc' WHERE TITLE = 'Priyotoma';
COMMIT;