-- ----------------------------
-- 100 additional Indian & Bangladeshi movies for CINEHIVE.MOVIE
-- MOVIE_ID range: 160-259 (continues after prior batch ending at 159)
-- ----------------------------
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('160', 'Sholay', TO_DATE('1975-08-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '204', 'Hindi', 'Two small-time criminals are hired by a former police officer to capture a ruthless bandit terrorizing his village.', 'https://www.youtube.com/watch?v=placeholder', NULL, '30000000', '3000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('161', 'Dilwale Dulhania Le Jayenge', TO_DATE('1995-10-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '190', 'Hindi', 'A young man falls in love with a woman promised to another, and must win over her traditional family.', 'https://www.youtube.com/watch?v=placeholder', NULL, '100000000', '2000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('162', 'Lagaan', TO_DATE('2001-06-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '224', 'Hindi', 'Villagers under British colonial rule wager their future on a high-stakes cricket match to escape crushing taxation.', 'https://www.youtube.com/watch?v=placeholder', NULL, '50000000', '6000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('163', '3 Idiots', TO_DATE('2009-12-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '170', 'Hindi', 'Two friends search for their long-lost college companion, recalling his unconventional approach to engineering and life.', 'https://www.youtube.com/watch?v=placeholder', NULL, '90000000', '10000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('164', 'Dangal', TO_DATE('2016-12-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '161', 'Hindi', 'A former wrestler trains his daughters to become world-class wrestlers, defying entrenched social expectations.', 'https://www.youtube.com/watch?v=placeholder', NULL, '311000000', '10000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('165', 'PK', TO_DATE('2014-12-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '153', 'Hindi', 'An alien stranded on Earth questions human religious customs while searching for a way back home.', 'https://www.youtube.com/watch?v=placeholder', NULL, '140000000', '18000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('166', 'Gangs of Wasseypur', TO_DATE('2012-06-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '321', 'Hindi', 'A multi-generational blood feud unfolds between rival coal-mining families in the badlands of Jharkhand.', 'https://www.youtube.com/watch?v=placeholder', NULL, '4600000', '2900000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('167', 'Zindagi Na Milegi Dobara', TO_DATE('2011-07-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '155', 'Hindi', 'Three friends confront long-buried fears and unresolved feelings during a bachelor road trip across Spain.', 'https://www.youtube.com/watch?v=placeholder', NULL, '45000000', '10000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('168', 'Queen', TO_DATE('2014-03-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '146', 'Hindi', 'A jilted bride embarks solo on her honeymoon and discovers unexpected independence and self-worth.', 'https://www.youtube.com/watch?v=placeholder', NULL, '27000000', '2700000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('169', 'Andhadhun', TO_DATE('2018-10-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '139', 'Hindi', 'A blind pianist becomes entangled in a murder investigation after witnessing more than he should have.', 'https://www.youtube.com/watch?v=placeholder', NULL, '38000000', '3300000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('170', 'Article 15', TO_DATE('2019-06-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '130', 'Hindi', 'A newly posted police officer investigates the disappearance of two girls in a caste-divided rural district.', 'https://www.youtube.com/watch?v=placeholder', NULL, '17000000', '4500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('171', 'The Lunchbox', TO_DATE('2013-09-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '104', 'Hindi', 'A misdelivered lunchbox sparks an unlikely written correspondence between a lonely housewife and a widower.', 'https://www.youtube.com/watch?v=placeholder', NULL, '17000000', '1000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('172', 'Gully Boy', TO_DATE('2019-02-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '153', 'Hindi', 'A young man from Mumbai''s slums pursues his passion for rap music to escape a life mapped out for him.', 'https://www.youtube.com/watch?v=placeholder', NULL, '32000000', '8500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('173', 'Taare Zameen Par', TO_DATE('2007-12-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '165', 'Hindi', 'An artistic teacher helps a struggling dyslexic child rediscover his confidence and creative gifts.', 'https://www.youtube.com/watch?v=placeholder', NULL, '20500000', '3500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('174', 'Rang De Basanti', TO_DATE('2006-01-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '167', 'Hindi', 'A documentary filmmaker''s college-age actors are radicalized into activism after a friend''s preventable death.', 'https://www.youtube.com/watch?v=placeholder', NULL, '20000000', '7000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('175', 'Barfi!', TO_DATE('2012-09-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '151', 'Hindi', 'A deaf and mute young man''s playful romances intertwine with the life of an autistic woman.', 'https://www.youtube.com/watch?v=placeholder', NULL, '32000000', '10500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('176', 'Kahaani', TO_DATE('2012-03-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '122', 'Hindi', 'A pregnant woman searches Kolkata for her missing husband, uncovering a conspiracy far larger than she expected.', 'https://www.youtube.com/watch?v=placeholder', NULL, '16000000', '2000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('177', 'Talvar', TO_DATE('2015-10-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '132', 'Hindi', 'Investigators offer conflicting theories in a real double murder case that gripped and divided the nation.', 'https://www.youtube.com/watch?v=placeholder', NULL, '7400000', '2000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('178', 'Uri: The Surgical Strike', TO_DATE('2019-01-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '138', 'Hindi', 'An army officer leads a covert retaliatory strike after a deadly attack on an Indian army base.', 'https://www.youtube.com/watch?v=placeholder', NULL, '75000000', '5900000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('179', 'Pink', TO_DATE('2016-09-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '136', 'Hindi', 'Three young women fight a courtroom battle after a harassment complaint spirals into a criminal case.', 'https://www.youtube.com/watch?v=placeholder', NULL, '14000000', '2800000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('180', 'Masaan', TO_DATE('2015-07-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '109', 'Hindi', 'Two parallel stories of grief and forbidden love unfold along the sacred banks of the Ganges in Varanasi.', 'https://www.youtube.com/watch?v=placeholder', NULL, '2100000', '600000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('181', 'Newton', TO_DATE('2017-09-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '106', 'Hindi', 'An idealistic government clerk is sent to conduct elections in a conflict-riddled forest region.', 'https://www.youtube.com/watch?v=placeholder', NULL, '5000000', '1000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('182', 'Tumbbad', TO_DATE('2018-10-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '104', 'Hindi', 'A family guards a cursed ancestral treasure protected by a monstrous deity that demands terrible sacrifice.', 'https://www.youtube.com/watch?v=placeholder', NULL, '3400000', '700000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('183', 'Stree', TO_DATE('2018-08-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '125', 'Hindi', 'A small town is terrorized by a spirit that abducts men at night, leaving only their clothes behind.', 'https://www.youtube.com/watch?v=placeholder', NULL, '75000000', '4300000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('184', 'Bajrangi Bhaijaan', TO_DATE('2015-07-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '163', 'Hindi', 'A devout man helps a mute Pakistani girl separated from her family find her way home across the border.', 'https://www.youtube.com/watch?v=placeholder', NULL, '195000000', '12000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('185', 'Swades', TO_DATE('2004-12-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '210', 'Hindi', 'A NASA scientist returns to his ancestral Indian village and rediscovers his roots while confronting rural hardship.', 'https://www.youtube.com/watch?v=placeholder', NULL, '9000000', '7500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('186', 'Rockstar', TO_DATE('2011-11-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '159', 'Hindi', 'A college musician chases heartbreak to fuel his art, transforming pain into a meteoric rise to fame.', 'https://www.youtube.com/watch?v=placeholder', NULL, '35000000', '10500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('187', 'Kal Ho Naa Ho', TO_DATE('2003-11-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '186', 'Hindi', 'A terminally ill man secretly orchestrates a romance between his neighbor and her reluctant best friend.', 'https://www.youtube.com/watch?v=placeholder', NULL, '44000000', '6000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('188', 'Devdas', TO_DATE('2002-07-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '185', 'Hindi', 'A wealthy man''s forbidden love is shattered by his family''s rejection, sending him into self-destructive despair.', 'https://www.youtube.com/watch?v=placeholder', NULL, '36000000', '15000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('189', 'Chennai Express', TO_DATE('2013-08-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '141', 'Hindi', 'A man''s plan for a solo vacation is derailed when he becomes entangled with a runaway bride and her gangster family.', 'https://www.youtube.com/watch?v=placeholder', NULL, '130000000', '12000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('190', 'Padmaavat', TO_DATE('2018-01-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '164', 'Hindi', 'A ruthless sultan''s obsession with a legendary queen leads his army to besiege her husband''s kingdom.', 'https://www.youtube.com/watch?v=placeholder', NULL, '117000000', '25500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('191', 'Mughal-E-Azam', TO_DATE('1960-08-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '197', 'Hindi', 'A Mughal prince''s forbidden love for a court dancer draws him into direct conflict with his emperor father.', 'https://www.youtube.com/watch?v=placeholder', NULL, '11000000', '10500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('192', 'Nayakan', TO_DATE('1987-11-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '145', 'Tamil', 'A young boy who witnesses his father''s murder grows into a powerful, morally complex crime boss in Mumbai''s slums.', 'https://www.youtube.com/watch?v=placeholder', NULL, '1500000', '1000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('193', 'Baasha', TO_DATE('1995-01-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '166', 'Tamil', 'A mild-mannered auto-rickshaw driver''s violent past as a Mumbai don resurfaces to threaten his quiet new life.', 'https://www.youtube.com/watch?v=placeholder', NULL, '2000000', '700000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('194', 'Vikram', TO_DATE('2022-06-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '174', 'Tamil', 'A special task force investigates a series of murders that uncovers a much larger criminal conspiracy.', 'https://www.youtube.com/watch?v=placeholder', NULL, '150000000', '45000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('195', 'Master', TO_DATE('2021-01-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '179', 'Tamil', 'An alcoholic professor is sent to a juvenile school, where he clashes with a former student turned gangster.', 'https://www.youtube.com/watch?v=placeholder', NULL, '63000000', '19000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('196', 'Kaithi', TO_DATE('2019-10-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '145', 'Tamil', 'A newly released convict is forced back into danger to protect a group of police officers under siege.', 'https://www.youtube.com/watch?v=placeholder', NULL, '23000000', '8000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('197', 'Vikram Vedha', TO_DATE('2017-07-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '147', 'Tamil', 'A principled police officer''s moral certainty is shattered by the philosophical riddles of the gangster he hunts.', 'https://www.youtube.com/watch?v=placeholder', NULL, '11000000', '3600000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('198', '96', TO_DATE('2018-10-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '158', 'Tamil', 'Former high school sweethearts reconnect at a reunion, reawakening feelings neither fully let go of.', 'https://www.youtube.com/watch?v=placeholder', NULL, '17000000', '3500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('199', 'Super Deluxe', TO_DATE('2019-03-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '176', 'Tamil', 'Several interwoven lives collide over one chaotic day, exposing hidden secrets and moral contradictions.', 'https://www.youtube.com/watch?v=placeholder', NULL, '2700000', '1500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('200', 'Jai Bhim', TO_DATE('2021-11-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '164', 'Tamil', 'A lawyer fights to secure justice for a tribal man wrongfully imprisoned and abused in police custody.', 'https://www.youtube.com/watch?v=placeholder', NULL, '1000000', '7000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('201', 'Soorarai Pottru', TO_DATE('2020-11-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '153', 'Tamil', 'An ambitious son of a farmer battles entrenched interests to launch India''s first low-cost airline.', 'https://www.youtube.com/watch?v=placeholder', NULL, '6000000', '16500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('202', 'Asuran', TO_DATE('2019-10-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '141', 'Tamil', 'A farmer''s violent past resurfaces as he fights to protect his family from a powerful, vengeful landlord.', 'https://www.youtube.com/watch?v=placeholder', NULL, '20000000', '6500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('203', 'Pariyerum Perumal', TO_DATE('2018-09-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '153', 'Tamil', 'A law student''s friendship with a woman from a higher caste exposes him to brutal social discrimination.', 'https://www.youtube.com/watch?v=placeholder', NULL, '2000000', '900000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('204', 'Visaranai', TO_DATE('2015-11-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '118', 'Tamil', 'Migrant workers are wrongfully arrested and tortured by police desperate to close an unsolved robbery case.', 'https://www.youtube.com/watch?v=placeholder', NULL, '1500000', '700000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('205', 'Kabali', TO_DATE('2016-07-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '151', 'Tamil', 'A released gang leader seeks to rebuild his organization and rescue his family from rival crime networks.', 'https://www.youtube.com/watch?v=placeholder', NULL, '45000000', '17000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('206', 'Enthiran', TO_DATE('2010-10-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '159', 'Tamil', 'A brilliant scientist''s humanoid robot creation develops emotions and spirals dangerously out of control.', 'https://www.youtube.com/watch?v=placeholder', NULL, '95000000', '29500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('207', 'Baahubali: The Beginning', TO_DATE('2015-07-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '159', 'Telugu', 'A young man raised in a remote village discovers his royal lineage and a kingdom''s dark, buried history.', 'https://www.youtube.com/watch?v=placeholder', NULL, '103000000', '25000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('208', 'Baahubali 2: The Conclusion', TO_DATE('2017-04-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '167', 'Telugu', 'The saga concludes as the truth behind a king''s betrayal and exile is finally revealed.', 'https://www.youtube.com/watch?v=placeholder', NULL, '277000000', '45000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('209', 'RRR', TO_DATE('2022-03-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '187', 'Telugu', 'Two real-life revolutionaries form a fictional bond of friendship before their paths diverge in colonial India.', 'https://www.youtube.com/watch?v=placeholder', NULL, '175000000', '72000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('210', 'Arjun Reddy', TO_DATE('2017-08-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '182', 'Telugu', 'A talented but self-destructive surgeon spirals into alcoholism and rage after losing the woman he loves.', 'https://www.youtube.com/watch?v=placeholder', NULL, '10000000', '2500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('211', 'Rangasthalam', TO_DATE('2018-03-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '171', 'Telugu', 'A hearing-impaired man confronts corrupt village leadership after uncovering a decades-long political conspiracy.', 'https://www.youtube.com/watch?v=placeholder', NULL, '38000000', '7000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('212', 'Pushpa: The Rise', TO_DATE('2021-12-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '179', 'Telugu', 'A laborer rises through the ranks of a red sandalwood smuggling syndicate, clashing with a relentless new officer.', 'https://www.youtube.com/watch?v=placeholder', NULL, '190000000', '42000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('213', 'Ala Vaikunthapurramuloo', TO_DATE('2020-01-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '166', 'Telugu', 'A man swapped at birth navigates two very different families while chasing his own long-buried destiny.', 'https://www.youtube.com/watch?v=placeholder', NULL, '93000000', '11500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('214', 'Eega', TO_DATE('2012-07-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '134', 'Telugu', 'A murdered man is reincarnated as a housefly and seeks revenge against the man who killed him.', 'https://www.youtube.com/watch?v=placeholder', NULL, '36000000', '14000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('215', 'Magadheera', TO_DATE('2009-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '156', 'Telugu', 'A modern-day stunt performer discovers he is the reincarnation of a warrior separated from his lover by tragedy.', 'https://www.youtube.com/watch?v=placeholder', NULL, '45000000', '20000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('216', 'Jersey', TO_DATE('2019-04-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '157', 'Telugu', 'A failed cricketer stages an unlikely comeback in his late thirties to fulfill a promise to his young son.', 'https://www.youtube.com/watch?v=placeholder', NULL, '5600000', '2200000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('217', 'Drishyam', TO_DATE('2013-07-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '160', 'Malayalam', 'A family man goes to extraordinary lengths to protect his family after covering up an accidental death.', 'https://www.youtube.com/watch?v=placeholder', NULL, '20000000', '3000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('218', 'Kumbalangi Nights', TO_DATE('2019-05-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '135', 'Malayalam', 'Four brothers with dysfunctional relationships slowly rebuild their bond in a coastal fishing village.', 'https://www.youtube.com/watch?v=placeholder', NULL, '7300000', '1000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('219', 'Premam', TO_DATE('2015-06-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '156', 'Malayalam', 'A young man''s romantic misadventures unfold across three distinct chapters of his life.', 'https://www.youtube.com/watch?v=placeholder', NULL, '14000000', '2000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('220', 'Bangalore Days', TO_DATE('2014-07-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '151', 'Malayalam', 'Three cousins navigate love, ambition, and personal crises after relocating together to the city.', 'https://www.youtube.com/watch?v=placeholder', NULL, '17000000', '2600000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('221', 'Maheshinte Prathikaram', TO_DATE('2016-02-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '127', 'Malayalam', 'A small-town photographer trains obsessively for a rematch after being publicly humiliated in a fight.', 'https://www.youtube.com/watch?v=placeholder', NULL, '5000000', '600000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('222', 'Angamaly Diaries', TO_DATE('2017-03-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '129', 'Malayalam', 'A young man''s rise in the local pork business draws him into gang rivalries in a small Kerala town.', 'https://www.youtube.com/watch?v=placeholder', NULL, '3800000', '750000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('223', 'Jallikattu', TO_DATE('2019-10-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '91', 'Malayalam', 'A buffalo''s escape from a slaughterhouse sends an entire village into a chaotic, primal frenzy.', 'https://www.youtube.com/watch?v=placeholder', NULL, '1000000', '700000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('224', 'Joji', TO_DATE('2021-04-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '115', 'Malayalam', 'An ambitious younger son plots against his domineering family after his patriarch father falls gravely ill.', 'https://www.youtube.com/watch?v=placeholder', NULL, '1200000', '900000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('225', 'The Great Indian Kitchen', TO_DATE('2021-01-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '100', 'Malayalam', 'A newlywed woman''s daily domestic servitude gradually exposes the quiet oppression of traditional gender roles.', 'https://www.youtube.com/watch?v=placeholder', NULL, '500000', '300000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('226', 'Lucifer', TO_DATE('2019-03-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '175', 'Malayalam', 'A political dynasty descends into crisis after its chief minister''s death, drawing a mysterious outsider into the power struggle.', 'https://www.youtube.com/watch?v=placeholder', NULL, '37000000', '9500000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('227', 'Pather Panchali', TO_DATE('1955-08-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '125', 'Bengali', 'A poor rural family in Bengal endures hardship and loss, seen through the eyes of their young son.', 'https://www.youtube.com/watch?v=placeholder', NULL, '700000', '17000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('228', 'Aparajito', TO_DATE('1956-11-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '113', 'Bengali', 'A young man torn between his widowed mother and his growing ambitions pursues education in the city.', 'https://www.youtube.com/watch?v=placeholder', NULL, '400000', '120000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('229', 'Apur Sansar', TO_DATE('1959-05-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '106', 'Bengali', 'A struggling writer''s unexpected marriage and subsequent fatherhood reshape his understanding of loss and love.', 'https://www.youtube.com/watch?v=placeholder', NULL, '300000', '150000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('230', 'Charulata', TO_DATE('1964-04-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '117', 'Bengali', 'A neglected wife in 19th-century Calcutta develops a quiet emotional bond with her husband''s visiting cousin.', 'https://www.youtube.com/watch?v=placeholder', NULL, '250000', '100000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('231', 'Nayak', TO_DATE('1966-05-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '122', 'Bengali', 'A famous film star reflects on the hollowness of fame during a long train journey with a young journalist.', 'https://www.youtube.com/watch?v=placeholder', NULL, '300000', '110000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('232', 'Sonar Kella', TO_DATE('1974-12-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '125', 'Bengali', 'A detective and his companions pursue a mystery surrounding a young boy''s visions of a golden fortress.', 'https://www.youtube.com/watch?v=placeholder', NULL, '500000', '150000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('233', 'Goopy Gyne Bagha Byne', TO_DATE('1969-05-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '132', 'Bengali', 'Two inept musicians granted magical boons by a ghost king use their gifts to stop a senseless war.', 'https://www.youtube.com/watch?v=placeholder', NULL, '400000', '80000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('234', 'Sairat', TO_DATE('2016-04-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '174', 'Marathi', 'Young lovers from starkly different castes elope, facing brutal consequences for defying rigid social hierarchies.', 'https://www.youtube.com/watch?v=placeholder', NULL, '48000000', '2000000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('235', 'Jibon Theke Neya', TO_DATE('1970-04-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '144', 'Bengali', 'A large joint family''s internal power struggles serve as an allegory for political repression under authoritarian rule.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('236', 'Titas Ekti Nadir Naam', TO_DATE('1973-09-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '159', 'Bengali', 'Fishing communities along a slowly dying river confront poverty, tradition, and the erosion of their way of life.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('237', 'Surjo Dighal Bari', TO_DATE('1979-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '121', 'Bengali', 'A destitute rural family struggles for survival and dignity in the harsh aftermath of famine and social neglect.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('238', 'Ghuddi', TO_DATE('1980-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '110', 'Bengali', 'A young boy infatuated with cinema navigates the gap between his fantasies and the realities of family life.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('239', 'Sareng Bou', TO_DATE('1978-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '130', 'Bengali', 'A riverboat captain''s devoted wife waits through long separations shaped by the rhythms of river trade.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('240', 'Beder Meye Josna', TO_DATE('1989-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '140', 'Bengali', 'A snake-charmer clan''s daughter falls in love across tribal lines, defying the customs of her nomadic community.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('241', 'Ora Egaro Jon', TO_DATE('1972-03-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '130', 'Bengali', 'A group of freedmen fighters band together during the 1971 Liberation War to resist occupying forces.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('242', 'Lalsalu', TO_DATE('2001-05-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '95', 'Bengali', 'A cunning wanderer exploits religious faith to seize control over a superstitious rural village.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('243', 'Matir Moina', TO_DATE('2002-05-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '98', 'Bengali', 'A young boy sent to a rigid religious school grapples with faith, family, and a country on the edge of change.', 'https://www.youtube.com/watch?v=placeholder', NULL, '120000', '300000', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('244', 'Shyamol Chhaya', TO_DATE('2004-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '100', 'Bengali', 'A group of refugees and freedom fighters shelter together in a village during the turmoil of 1971.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('245', 'Monpura', TO_DATE('2009-10-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '130', 'Bengali', 'A young man exiled to a remote river island falls into a complicated love triangle with local villagers.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('246', 'Third Person Singular Number', TO_DATE('2009-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '93', 'Bengali', 'A young woman navigates independence and hardship in Dhaka while awaiting her husband''s return from abroad.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('247', 'Gerilla', TO_DATE('2011-03-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '115', 'Bengali', 'A woman secretly aids the resistance movement while her husband is held captive during the 1971 war.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('248', 'Television', TO_DATE('2012-12-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '105', 'Bengali', 'A conservative village leader''s ban on television is quietly defied by residents eager for connection to the outside world.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('249', 'Aynabaji', TO_DATE('2016-10-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '143', 'Bengali', 'A professional impersonator who stands in for defendants in court finds his double life spiraling out of control.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('250', 'Dhaka Attack', TO_DATE('2017-08-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '140', 'Bengali', 'An elite police officer investigates a covert terror network plotting an attack on the capital.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('251', 'Debi', TO_DATE('2018-10-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '107', 'Bengali', 'A woman''s disturbing supernatural visions draw a detective into a mystery rooted in an old psychiatric case.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('252', 'Fagun Hawa', TO_DATE('2019-03-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '107', 'Bengali', 'Students in a small town are swept up in the 1952 language movement, risking everything for their mother tongue.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('253', 'Made in Bangladesh', TO_DATE('2019-05-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '95', 'Bengali', 'Garment factory workers organize to form a union despite intense pressure from management and their own families.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('254', 'No Dorai', TO_DATE('2019-12-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '143', 'Bengali', 'A young woman from a coastal village pursues a dream of competitive surfing against her family''s wishes.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('255', 'Rehana Maryam Noor', TO_DATE('2021-07-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '115', 'Bengali', 'A medical college professor risks her career to seek justice after witnessing the harassment of a student.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('256', 'Hawa', TO_DATE('2022-07-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '130', 'Bengali', 'Tensions and superstition rise among a fishing crew after a mysterious woman is found aboard their boat at sea.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('257', 'Poran', TO_DATE('2022-06-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '153', 'Bengali', 'A love triangle in rural Bangladesh escalates into tragedy as old rivalries and new desires collide.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('258', 'Damal', TO_DATE('2022-06-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '150', 'Bengali', 'Bengali footballers form a team to raise funds for the resistance during the 1971 Liberation War.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');
INSERT INTO "CINEHIVE"."MOVIE" VALUES ('259', 'Priyotoma', TO_DATE('2023-11-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '150', 'Bengali', 'An expatriate driver''s love for a wealthy woman is tested by class differences and years of separation.', 'https://www.youtube.com/watch?v=placeholder', NULL, '0', '0', NULL, '0');

-- ----------------------------
-- Genre links for the 100 new movies
-- ----------------------------
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('160', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('160', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('161', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('161', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('162', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('162', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('163', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('163', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('164', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('164', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('165', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('165', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('166', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('166', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('167', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('167', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('168', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('168', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('169', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('169', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('170', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('170', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('171', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('171', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('172', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('172', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('173', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('174', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('174', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('175', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('175', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('176', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('177', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('177', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('178', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('178', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('179', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('179', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('180', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('181', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('181', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('182', '3');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('182', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('183', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('183', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('184', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('184', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('185', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('186', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('186', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('187', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('187', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('188', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('189', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('189', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('190', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('190', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('191', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('192', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('192', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('193', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('193', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('194', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('194', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('195', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('195', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('196', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('196', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('197', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('197', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('198', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('199', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('200', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('200', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('201', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('202', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('202', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('203', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('204', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('204', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('205', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('205', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('206', '3');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('206', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('207', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('207', '6');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('208', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('208', '6');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('209', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('209', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('210', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('211', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('211', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('212', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('212', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('213', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('213', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('214', '3');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('214', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('215', '6');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('215', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('216', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('217', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('217', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('218', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('218', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('219', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('219', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('220', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('220', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('221', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('221', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('222', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('222', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('223', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('223', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('224', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('224', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('225', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('226', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('226', '7');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('227', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('228', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('229', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('230', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('231', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('232', '6');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('232', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('233', '8');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('233', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('234', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('234', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('235', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('236', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('237', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('238', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('238', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('239', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('240', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('240', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('241', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('241', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('242', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('243', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('244', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('245', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('245', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('246', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('247', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('247', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('248', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('248', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('249', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('249', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('250', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('250', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('251', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('251', '3');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('252', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('253', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('254', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('254', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('255', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('255', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('256', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('256', '4');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('257', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('257', '5');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('258', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('258', '1');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('259', '2');
INSERT INTO "CINEHIVE"."MOVIE_GENRE" VALUES ('259', '5');